// Bundle the CLI engine adapter (Phase R3b) into a single self-contained
// `lib/engine.mjs` at the repo root, so the bash CLI can spawn it without any
// node_modules resolution — and so it ships in the npm tarball (files: ["lib/"]).
//
// Bundles the COMPILED dist/cli.js (not src) so `./index.js`-style imports
// resolve to real files. Run AFTER `npm run -w shared build`.
//   node shared/scripts/build-engine.mjs
// Wired as `npm run build:data` → engine, and drift-checked in ci-pre-push.sh.
import { build } from 'esbuild'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const sharedRoot = join(here, '..')
const repoRoot = join(sharedRoot, '..')

const common = {
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node18',
  // Deterministic output (no timestamp/path noise) — the bundles are committed
  // and drift-checked, so byte-stability across machines matters.
  banner: {
    js: '// GENERATED by shared/scripts/build-engine.mjs — do not edit. Run `npm run build:data`.',
  },
  legalComments: 'none',
}

// The CLI engine adapter (spawned by the bash bridge).
await build({
  ...common,
  entryPoints: [join(sharedRoot, 'dist', 'cli.js')],
  outfile: join(repoRoot, 'lib', 'engine.mjs'),
})
console.log('Wrote lib/engine.mjs')

// The native statusline entrypoint (Phase R3d-5 — in-process, no spawn).
await build({
  ...common,
  entryPoints: [join(sharedRoot, 'dist', 'statusline-entry.js')],
  outfile: join(repoRoot, 'lib', 'statusline.mjs'),
})
console.log('Wrote lib/statusline.mjs')

// The native /pokemon dispatcher (Phase R3d-5 — in-process).
await build({
  ...common,
  entryPoints: [join(sharedRoot, 'dist', 'pokemon-entry.js')],
  outfile: join(repoRoot, 'lib', 'pokemon.mjs'),
})
console.log('Wrote lib/pokemon.mjs')
