// GENERATED by shared/scripts/build-engine.mjs — do not edit. Run `npm run build:data`.

// dist/cli.js
import { fileURLToPath } from "node:url";
import { realpathSync } from "node:fs";

// dist/render/printf.js
var VALID_SPEC = /^%[-+ 0]*\d*(?:\.\d+)?[sdi]/;
function byteLen(s) {
  return Buffer.byteLength(s, "utf8");
}
function truncateBytes(s, n) {
  if (byteLen(s) <= n)
    return s;
  let out = "";
  let used = 0;
  for (const ch of s) {
    const b = byteLen(ch);
    if (used + b > n)
      break;
    out += ch;
    used += b;
  }
  return out;
}
function formatSpec(spec, raw) {
  const m = /^%([-+ 0]*)(\d*)(?:\.(\d+))?([sdi])$/.exec(spec);
  if (!m)
    return spec;
  const flags = m[1];
  const width = m[2] ? parseInt(m[2], 10) : 0;
  const prec = m[3] !== void 0 ? parseInt(m[3], 10) : void 0;
  const conv = m[4];
  const leftJustify = flags.includes("-");
  const zeroPad = flags.includes("0") && !leftJustify;
  let s;
  if (conv === "s") {
    s = raw === void 0 || raw === null ? "" : String(raw);
    if (prec !== void 0)
      s = truncateBytes(s, prec);
  } else {
    const n = raw === void 0 || raw === "" ? 0 : Math.trunc(Number(raw));
    s = String(Number.isNaN(n) ? 0 : n);
  }
  const len = byteLen(s);
  if (width > len) {
    const padLen = width - len;
    if (leftJustify) {
      s = s + " ".repeat(padLen);
    } else if (zeroPad && conv !== "s") {
      if (s.startsWith("-"))
        s = "-" + "0".repeat(padLen) + s.slice(1);
      else
        s = "0".repeat(padLen) + s;
    } else {
      s = " ".repeat(padLen) + s;
    }
  }
  return s;
}
function onePass(fmt, args, startAi) {
  let out = "";
  let ai = startAi;
  let hadConv = false;
  let i = 0;
  while (i < fmt.length) {
    const ch = fmt[i];
    if (ch !== "%") {
      out += ch;
      i++;
      continue;
    }
    if (fmt[i + 1] === "%") {
      out += "%";
      i += 2;
      continue;
    }
    const m = VALID_SPEC.exec(fmt.slice(i));
    if (!m)
      return { out, ai, truncated: true, hadConv };
    const spec = m[0];
    out += formatSpec(spec, args[ai++]);
    hadConv = true;
    i += spec.length;
  }
  return { out, ai, truncated: false, hadConv };
}
function bashPrintf(fmt, ...args) {
  let out = "";
  let ai = 0;
  for (; ; ) {
    const r = onePass(fmt, args, ai);
    out += r.out;
    ai = r.ai;
    if (r.truncated)
      break;
    if (!(ai < args.length && r.hadConv))
      break;
  }
  return out;
}

// dist/render/i18n.js
function localeLookup(locale, key) {
  const parts = key.split(".");
  let cur = locale;
  for (const p of parts) {
    if (cur == null)
      return void 0;
    if (Array.isArray(cur)) {
      const i = Number(p);
      cur = Number.isInteger(i) ? cur[i] : void 0;
    } else if (typeof cur === "object") {
      cur = cur[p];
    } else {
      return void 0;
    }
  }
  if (cur == null)
    return void 0;
  return typeof cur === "string" ? cur : String(cur);
}
function t(locale, key, ...args) {
  const result = localeLookup(locale, key) || key;
  return args.length > 0 ? bashPrintf(result, ...args) : result;
}

// dist/render/views.js
var RESET = "\x1B[0m";
var BOLD = "\x1B[1m";
var DIM = "\x1B[2m";
var GOLD = "\x1B[33m";
function jqStr(v) {
  return v === null || v === void 0 ? "null" : String(v);
}
function padChars(s, width) {
  const len = [...s].length;
  return s + " ".repeat(Math.max(0, width - len));
}
function tPad(locale, key, width) {
  return padChars(t(locale, key), width);
}
function fmtInt(n) {
  let s = String(Math.trunc(Number(n) || 0));
  let neg = "";
  if (s.startsWith("-")) {
    neg = "-";
    s = s.slice(1);
  }
  let out = "";
  while (s.length > 3) {
    out = " " + s.slice(-3) + out;
    s = s.slice(0, -3);
  }
  return neg + s + out;
}
var BADGE_EMOJI = {
  hatch: "\u{1F95A}",
  first_evolution: "\u{1F331}",
  first_shiny: "\u2B50",
  champion: "\u{1F3C6}",
  centurion: "\u{1F4AF}",
  constellation: "\u{1F30C}",
  master_pokedex: "\u{1F48E}",
  dex_50: "\u{1F52C}",
  dex_100: "\u{1F4DA}",
  regional_kanto: "\u{1F3D4}\uFE0F",
  regional_johto: "\u{1F3EF}",
  master_fire: "\u{1F525}",
  master_water: "\u{1F4A7}",
  master_grass: "\u{1F33F}",
  master_electric: "\u26A1",
  master_eevee: "\u{1F98A}",
  master_chikorita: "\u{1F343}",
  master_cyndaquil: "\u{1F994}",
  master_totodile: "\u{1F40A}"
};
var BADGE_ORDER = [
  "hatch",
  "first_evolution",
  "first_shiny",
  "champion",
  "centurion",
  "constellation",
  "master_pokedex",
  "master_fire",
  "master_water",
  "master_grass",
  "master_electric",
  "master_eevee",
  "master_chikorita",
  "master_cyndaquil",
  "master_totodile"
];
function renderBadges(ctx) {
  const { state, locale } = ctx;
  let out = bashPrintf(`
  %s%s${t(locale, "badges.title")}%s

`, BOLD, GOLD, RESET);
  const badges = Array.isArray(state.badges) ? state.badges : [];
  for (const id of BADGE_ORDER) {
    const earnedAt = badges.find((b) => b && b.id === id)?.earned_at ?? "";
    const emoji = BADGE_EMOJI[id] ?? "?";
    const label = t(locale, `badges.${id}.0`);
    const desc = t(locale, `badges.${id}.1`);
    if (earnedAt) {
      out += bashPrintf("   %s  %s%-22s%s  %s%s%s\n     %s%s%s\n", emoji, BOLD, label, RESET, GOLD, String(earnedAt).slice(0, 10), RESET, DIM, desc, RESET);
    } else {
      out += bashPrintf("   %s%s  %-22s%s\n     %s%s%s\n", DIM, "\u25A2", label, RESET, DIM, desc, RESET);
    }
  }
  out += "\n";
  return out;
}
function renderInventory(ctx) {
  const { state, data, locale } = ctx;
  let out = bashPrintf(`
  %s%s${t(locale, "inventory.title")}%s

`, BOLD, GOLD, RESET);
  const items = state.items && typeof state.items === "object" ? state.items : {};
  const entries = Object.entries(items);
  if (entries.length === 0) {
    out += bashPrintf(`  %s${t(locale, "inventory.empty")}%s

`, DIM, RESET);
  } else {
    for (const [itemId, qty] of entries) {
      const meta = data.items?.[itemId];
      const name = meta?.name ?? itemId;
      const emoji = meta?.emoji ?? "?";
      const desc = meta?.desc ?? "";
      out += bashPrintf("   %s  %s%-18s%s  %s\xD7%d%s\n     %s%s%s\n", emoji, BOLD, name, RESET, DIM, Number(qty), RESET, DIM, desc, RESET);
    }
    out += "\n";
  }
  const eeveeForm = state.eevee_form ?? "";
  if (eeveeForm) {
    const stages = data.lineages?.eevee?.stages ?? [];
    const formName = stages.find((s) => s && s.showdown_id === eeveeForm)?.name;
    const msg = t(locale, "inventory.eevee_form", formName);
    out += bashPrintf("  %s%s%s\n\n", DIM, msg, RESET);
  }
  return out;
}
function renderRoster(ctx, field, title) {
  const { state, data } = ctx;
  let out = bashPrintf("\n  %s%s%s%s\n\n", BOLD, GOLD, title, RESET);
  const list = Array.isArray(state[field]) ? state[field] : [];
  if (list.length === 0) {
    out += bashPrintf(`  %s${t(ctx.locale, "team.empty")}%s

`, DIM, RESET);
    return out;
  }
  let i = 0;
  for (const e of list) {
    const lin = jqStr(e.lineage);
    const star = e.is_shiny === true ? `${GOLD}\u2605${RESET} ` : "";
    const name = jqStr(e.max_stage);
    const lvl = Number(e.level);
    const label = data.lineages?.[lin]?.label ?? lin;
    const created = jqStr(e.created_at).slice(0, 10);
    const completed = jqStr(e.completed_at).slice(0, 10);
    out += bashPrintf("   %s[%d]%s  %s%-22s  %sLv.%d%s  %s%s%s  (%s%s%s \u2192 %s%s%s)\n", BOLD, i, RESET, star, name, BOLD, lvl, RESET, DIM, label, RESET, DIM, created, RESET, DIM, completed, RESET);
    i++;
  }
  out += "\n";
  return out;
}
function renderTeam(ctx) {
  let out = renderRoster(ctx, "team", t(ctx.locale, "team.title"));
  const pcCount = Array.isArray(ctx.state.pc_storage) ? ctx.state.pc_storage.length : 0;
  if (pcCount > 0) {
    out += bashPrintf(`  %s${t(ctx.locale, "team.pc_overflow")} \u2014 %sbash %s pc%s

`, DIM, pcCount, DIM, ctx.scriptName, RESET);
  }
  return out;
}
function renderPc(ctx) {
  return renderRoster(ctx, "pc_storage", t(ctx.locale, "pc.title"));
}
function renderStats(ctx) {
  const { state, data, locale } = ctx;
  const ls = state.lifetime_stats ?? {};
  let out = bashPrintf(`
  %s%s${t(locale, "stats.title")}%s

`, BOLD, GOLD, RESET);
  const shinies = Number(ls.total_shinies ?? 0);
  const completed = Array.isArray(ls.lineages_completed) ? ls.lineages_completed.length : 0;
  const totalLineages = Object.keys(data.lineages ?? {}).length;
  const firstShiny = ls.first_shiny_at ?? "\u2014";
  out += bashPrintf(`  %s${tPad(locale, "stats.total_tokens", 22)}%s :  %s
`, DIM, RESET, fmtInt(ls.total_tokens));
  out += bashPrintf(`  %s${tPad(locale, "stats.total_evolutions", 22)}%s :  %s
`, DIM, RESET, fmtInt(ls.total_evolutions));
  out += bashPrintf(`  %s${tPad(locale, "stats.total_shinies", 22)}%s :  %s
`, DIM, RESET, fmtInt(shinies));
  out += bashPrintf(`  %s${tPad(locale, "stats.max_level", 22)}%s :  Lv.%s
`, DIM, RESET, jqStr(ls.max_level));
  out += bashPrintf(`  %s${tPad(locale, "stats.total_compagnons", 22)}%s :  %s
`, DIM, RESET, fmtInt(ls.total_compagnons));
  out += bashPrintf(`  %s${tPad(locale, "stats.lineages_completed", 22)}%s :  %s / %s
`, DIM, RESET, completed, totalLineages);
  out += bashPrintf(`  %s${tPad(locale, "stats.first_shiny", 22)}%s :  %s

`, DIM, RESET, String(firstShiny).slice(0, 10));
  const mults = state.last_xp_multipliers;
  if (mults != null) {
    out += bashPrintf(`  %s%s${t(locale, "stats.multipliers_title")}%s

`, BOLD, GOLD, RESET);
    const ctxM = mults.context;
    const tm = mults.type_match;
    const db = mults.daily_bonus;
    const st = mults.status;
    out += bashPrintf(`  %s${tPad(locale, "stats.context", 22)}%s : \xD7%s
`, DIM, RESET, ctxM);
    out += bashPrintf(`  %s${tPad(locale, "stats.type_match", 22)}%s : \xD7%s
`, DIM, RESET, tm);
    out += bashPrintf(`  %s${tPad(locale, "stats.daily_bonus", 22)}%s : \xD7%s
`, DIM, RESET, db);
    out += bashPrintf(`  %s${tPad(locale, "stats.status", 22)}%s : \xD7%s
`, DIM, RESET, st);
    const combined = (Number(ctxM) * Number(tm) * Number(db) * Number(st)).toFixed(2);
    out += bashPrintf(`  %s${tPad(locale, "stats.combined", 22)}%s : %s\xD7%s%s

`, DIM, RESET, BOLD, combined, RESET);
  }
  const status = state.status ?? "ok";
  const streak = Number(state.high_context_streak ?? 0);
  if (status === "tired") {
    out += bashPrintf(`  %s${t(locale, "stats.tired_warning", streak)}%s

`, BOLD, RESET);
  }
  if (shinies > 0) {
    out += bashPrintf(`  %s${t(locale, "stats.shiny_charm")}%s

`, GOLD, RESET);
  }
  return out;
}
function renderPokedex(ctx) {
  const { state, data, locale } = ctx;
  let out = bashPrintf(`
  %s%s${t(locale, "pokedex.title_lineages")}%s

`, BOLD, GOLD, RESET);
  const dex = state.pokedex ?? {};
  for (const [lin, info] of Object.entries(data.lineages ?? {})) {
    const label = info.label;
    const entry = dex[lin] ?? {};
    const seen = entry.seen ?? false;
    const shiny = entry.shiny_seen ?? false;
    const count = Number(entry.count ?? 0);
    const shinyCount = Number(entry.shiny_count ?? 0);
    if (seen === true) {
      const shinyStr = shiny === true ? `  ${GOLD}${t(locale, "pokedex.shiny_seen")}${RESET}` : "";
      out += bashPrintf("   %s\u2713%s  %-20s %s\xD7%d   %s: %d%s\n", BOLD, RESET, label, DIM, count, t(locale, "pokedex.shinies"), shinyCount, shinyStr);
    } else {
      out += bashPrintf("   \u25A2  %s%-20s%s  %s\u2014%s\n", DIM, label, RESET, DIM, RESET);
    }
  }
  const wild = state.pokedex_wild ?? {};
  const wildSeen = Object.keys(wild).length;
  const pool = Array.isArray(data.wild_pool) ? data.wild_pool : [];
  const totalWild = pool.length;
  const lang = data.language ?? "fr";
  out += bashPrintf(`
  %s%s${t(locale, "pokedex.title_wild")}%s   %s(%d / %d)%s

`, BOLD, GOLD, RESET, DIM, wildSeen, totalWild, RESET);
  const sorted = [...pool].sort((a, b) => Number(a.national_dex) - Number(b.national_dex));
  let col = 0;
  for (const w of sorted) {
    const id = w.id;
    const seen = Object.prototype.hasOwnProperty.call(wild, id);
    const marker = seen ? `${BOLD}\u2713${RESET}` : `${DIM}\u25A2${RESET}`;
    const style = seen ? "" : DIM;
    const nameDisp = seen ? jqStr(w[`name_${lang}`]) : "???";
    const rarity = w.rarity ?? "common";
    const rarityMarker = rarity === "legendary" ? `${GOLD}\u2605${RESET}` : " ";
    out += bashPrintf("  %s #%03d %s %s%s%s", marker, Number(w.national_dex), rarityMarker, style, padChars(nameDisp, 12), RESET);
    col++;
    if (col >= 4) {
      out += "\n";
      col = 0;
    }
  }
  if (col > 0)
    out += "\n";
  out += "\n";
  return out;
}

// dist/render/index.js
var RENDERERS = {
  badges: renderBadges,
  inventory: renderInventory,
  team: renderTeam,
  pc: renderPc,
  stats: renderStats,
  pokedex: renderPokedex
};
var SUPPORTED_VIEWS = Object.keys(RENDERERS);
function renderView(input) {
  const renderer = RENDERERS[input.view];
  if (!renderer)
    return { supported: false, output: "" };
  const ctx = {
    state: input.state,
    data: input.data,
    locale: input.locale,
    lang: input.lang ?? "fr",
    scriptName: input.scriptName ?? "pokemon-status.sh"
  };
  return { supported: true, output: renderer(ctx) };
}

// dist/types.js
var COMBAT_TYPES = [
  "normal",
  "fire",
  "water",
  "electric",
  "grass",
  "ice",
  "fighting",
  "poison",
  "ground",
  "flying",
  "psychic",
  "bug",
  "rock",
  "ghost",
  "dragon",
  "dark",
  "steel",
  "fairy"
];

// dist/battle.js
var TYPE_CHART_OVERRIDES = {
  normal: { rock: 0.5, ghost: 0, steel: 0.5 },
  fire: { fire: 0.5, water: 0.5, grass: 2, ice: 2, bug: 2, rock: 0.5, dragon: 0.5, steel: 2 },
  water: { fire: 2, water: 0.5, grass: 0.5, ground: 2, rock: 2, dragon: 0.5 },
  electric: { water: 2, electric: 0.5, grass: 0.5, ground: 0, flying: 2, dragon: 0.5 },
  grass: {
    fire: 0.5,
    water: 2,
    grass: 0.5,
    poison: 0.5,
    ground: 2,
    flying: 0.5,
    bug: 0.5,
    rock: 2,
    dragon: 0.5,
    steel: 0.5
  },
  ice: { fire: 0.5, water: 0.5, grass: 2, ice: 0.5, ground: 2, flying: 2, dragon: 2, steel: 0.5 },
  fighting: {
    normal: 2,
    ice: 2,
    poison: 0.5,
    flying: 0.5,
    psychic: 0.5,
    bug: 0.5,
    rock: 2,
    ghost: 0,
    dark: 2,
    steel: 2,
    fairy: 0.5
  },
  poison: { grass: 2, poison: 0.5, ground: 0.5, rock: 0.5, ghost: 0.5, steel: 0, fairy: 2 },
  ground: { fire: 2, electric: 2, grass: 0.5, poison: 2, flying: 0, bug: 0.5, rock: 2, steel: 2 },
  flying: { electric: 0.5, grass: 2, fighting: 2, bug: 2, rock: 0.5, steel: 0.5 },
  psychic: { fighting: 2, poison: 2, psychic: 0.5, dark: 0, steel: 0.5 },
  bug: {
    fire: 0.5,
    grass: 2,
    fighting: 0.5,
    poison: 0.5,
    flying: 0.5,
    psychic: 2,
    ghost: 0.5,
    dark: 2,
    steel: 0.5,
    fairy: 0.5
  },
  rock: { fire: 2, ice: 2, fighting: 0.5, ground: 0.5, flying: 2, bug: 2, steel: 0.5 },
  ghost: { normal: 0, psychic: 2, ghost: 2, dark: 0.5 },
  dragon: { dragon: 2, steel: 0.5, fairy: 0 },
  dark: { fighting: 0.5, psychic: 2, ghost: 2, dark: 0.5, fairy: 0.5 },
  steel: { fire: 0.5, water: 0.5, electric: 0.5, ice: 2, rock: 2, steel: 0.5, fairy: 2 },
  fairy: { fire: 0.5, fighting: 2, poison: 0.5, dragon: 2, dark: 2, steel: 0.5 }
};
function buildTypeChart() {
  const chart = {};
  for (const attacker of COMBAT_TYPES) {
    chart[attacker] = {};
    for (const defender of COMBAT_TYPES) {
      chart[attacker][defender] = TYPE_CHART_OVERRIDES[attacker]?.[defender] ?? 1;
    }
  }
  return chart;
}
var TYPE_CHART = buildTypeChart();

// dist/xp.js
function thresholdFor(thresholds, level) {
  return thresholds[level];
}
function levelFromXp(thresholds, totalXp) {
  let count = 0;
  for (const t2 of thresholds)
    if (t2 <= totalXp)
      count++;
  return count - 1;
}
function xpToNext(thresholds, totalXp, level) {
  const maxLevel = thresholds.length - 1;
  if (level >= maxLevel)
    return 0;
  return thresholds[level + 1] - totalXp;
}
function progressPct(thresholds, totalXp, level) {
  const maxLevel = thresholds.length - 1;
  if (level >= maxLevel)
    return 100;
  const cur = thresholds[level];
  const nxt = thresholds[level + 1];
  const pct = Math.floor((totalXp - cur) * 100 / (nxt - cur));
  if (pct < 0)
    return 0;
  if (pct > 100)
    return 100;
  return pct;
}
function xpMultiplier(usedPct) {
  if (usedPct == null)
    return 1;
  const p = Math.round(usedPct);
  if (p <= 25)
    return 2;
  if (p <= 50)
    return 1.5;
  if (p <= 75)
    return 1;
  return 0.5;
}
function typeMatchMultiplier(lineage, usedPct) {
  const p = Math.round(usedPct);
  switch (lineage) {
    case "fire":
      return p < 30 ? 1.2 : 1;
    case "water":
      return p > 70 ? 1.2 : 1;
    case "grass":
      return p >= 40 && p <= 60 ? 1.2 : 1;
    case "electric":
      return 1.2;
    case "eevee":
      return 1.1;
    default:
      return 1;
  }
}

// dist/cli.js
function derive(input) {
  const { thresholds, lineage } = input;
  const totalXp = Number(input.total_xp);
  const usedPct = input.used_pct == null ? null : Number(input.used_pct);
  const level = input.level == null ? levelFromXp(thresholds, totalXp) : Number(input.level);
  const typeMatch = typeMatchMultiplier(lineage, usedPct == null ? 50 : usedPct);
  return {
    level,
    threshold: thresholdFor(thresholds, level),
    xp_to_next: xpToNext(thresholds, totalXp, level),
    progress_pct: progressPct(thresholds, totalXp, level),
    xp_multiplier: xpMultiplier(usedPct).toFixed(1),
    type_match_mult: typeMatch.toFixed(1)
  };
}
var COMMANDS = {
  derive: (input) => derive(input)
};
async function readStdin() {
  const chunks = [];
  for await (const chunk of process.stdin)
    chunks.push(chunk);
  return Buffer.concat(chunks).toString("utf8");
}
async function main() {
  const command = process.argv[2];
  const isRender = command === "render";
  const handler = command ? COMMANDS[command] : void 0;
  if (!handler && !isRender) {
    process.stderr.write(`engine: unknown command ${JSON.stringify(command)} (expected: ${[...Object.keys(COMMANDS), "render"].join(", ")})
`);
    process.exit(2);
  }
  const raw = await readStdin();
  let input;
  try {
    input = JSON.parse(raw);
  } catch {
    process.stderr.write("engine: invalid JSON on stdin\n");
    process.exit(2);
    return;
  }
  if (isRender) {
    const inp = input;
    const argView = process.argv[3];
    if (argView)
      inp.view = argView;
    const { supported, output } = renderView(inp);
    if (!supported)
      process.exit(3);
    process.stdout.write(output);
    return;
  }
  process.stdout.write(JSON.stringify(handler(input)));
}
function invokedAsScript() {
  const entry = process.argv[1];
  if (!entry)
    return false;
  try {
    return realpathSync(entry) === realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return false;
  }
}
if (invokedAsScript()) {
  main().catch((err) => {
    process.stderr.write(`engine: ${err instanceof Error ? err.message : String(err)}
`);
    process.exit(1);
  });
}
export {
  derive
};
