// GENERATED by shared/scripts/build-engine.mjs — do not edit. Run `npm run build:data`.

// dist/cli.js
import { fileURLToPath } from "node:url";
import { realpathSync } from "node:fs";

// dist/render/printf.js
var VALID_SPEC = /^%[-+ 0]*\d*(?:\.\d+)?[sdi]/;
function byteLen(s) {
  return Buffer.byteLength(s, "utf8");
}
function truncateBytes(s, n) {
  if (byteLen(s) <= n)
    return s;
  let out = "";
  let used = 0;
  for (const ch of s) {
    const b = byteLen(ch);
    if (used + b > n)
      break;
    out += ch;
    used += b;
  }
  return out;
}
function formatSpec(spec, raw) {
  const m = /^%([-+ 0]*)(\d*)(?:\.(\d+))?([sdi])$/.exec(spec);
  if (!m)
    return spec;
  const flags = m[1];
  const width = m[2] ? parseInt(m[2], 10) : 0;
  const prec = m[3] !== void 0 ? parseInt(m[3], 10) : void 0;
  const conv = m[4];
  const leftJustify = flags.includes("-");
  const zeroPad = flags.includes("0") && !leftJustify;
  let s;
  if (conv === "s") {
    s = raw === void 0 || raw === null ? "" : String(raw);
    if (prec !== void 0)
      s = truncateBytes(s, prec);
  } else {
    const n = raw === void 0 || raw === "" ? 0 : Math.trunc(Number(raw));
    s = String(Number.isNaN(n) ? 0 : n);
  }
  const len = byteLen(s);
  if (width > len) {
    const padLen = width - len;
    if (leftJustify) {
      s = s + " ".repeat(padLen);
    } else if (zeroPad && conv !== "s") {
      if (s.startsWith("-"))
        s = "-" + "0".repeat(padLen) + s.slice(1);
      else
        s = "0".repeat(padLen) + s;
    } else {
      s = " ".repeat(padLen) + s;
    }
  }
  return s;
}
function onePass(fmt, args, startAi) {
  let out = "";
  let ai = startAi;
  let hadConv = false;
  let i = 0;
  while (i < fmt.length) {
    const ch = fmt[i];
    if (ch !== "%") {
      out += ch;
      i++;
      continue;
    }
    if (fmt[i + 1] === "%") {
      out += "%";
      i += 2;
      continue;
    }
    const m = VALID_SPEC.exec(fmt.slice(i));
    if (!m)
      return { out, ai, truncated: true, hadConv };
    const spec = m[0];
    out += formatSpec(spec, args[ai++]);
    hadConv = true;
    i += spec.length;
  }
  return { out, ai, truncated: false, hadConv };
}
function bashPrintf(fmt, ...args) {
  let out = "";
  let ai = 0;
  for (; ; ) {
    const r = onePass(fmt, args, ai);
    out += r.out;
    ai = r.ai;
    if (r.truncated)
      break;
    if (!(ai < args.length && r.hadConv))
      break;
  }
  return out;
}

// dist/render/i18n.js
function localeLookup(locale, key) {
  const parts = key.split(".");
  let cur = locale;
  for (const p of parts) {
    if (cur == null)
      return void 0;
    if (Array.isArray(cur)) {
      const i = Number(p);
      cur = Number.isInteger(i) ? cur[i] : void 0;
    } else if (typeof cur === "object") {
      cur = cur[p];
    } else {
      return void 0;
    }
  }
  if (cur == null)
    return void 0;
  return typeof cur === "string" ? cur : String(cur);
}
function t(locale, key, ...args) {
  const result = localeLookup(locale, key) || key;
  return args.length > 0 ? bashPrintf(result, ...args) : result;
}

// dist/render/views.js
var RESET = "\x1B[0m";
var BOLD = "\x1B[1m";
var DIM = "\x1B[2m";
var GOLD = "\x1B[33m";
function jqStr(v) {
  return v === null || v === void 0 ? "null" : String(v);
}
function padChars(s, width) {
  const len = [...s].length;
  return s + " ".repeat(Math.max(0, width - len));
}
function tPad(locale, key, width) {
  return padChars(t(locale, key), width);
}
function fmtInt(n) {
  let s = String(Math.trunc(Number(n) || 0));
  let neg = "";
  if (s.startsWith("-")) {
    neg = "-";
    s = s.slice(1);
  }
  let out = "";
  while (s.length > 3) {
    out = " " + s.slice(-3) + out;
    s = s.slice(0, -3);
  }
  return neg + s + out;
}
var BADGE_EMOJI = {
  hatch: "\u{1F95A}",
  first_evolution: "\u{1F331}",
  first_shiny: "\u2B50",
  champion: "\u{1F3C6}",
  centurion: "\u{1F4AF}",
  constellation: "\u{1F30C}",
  master_pokedex: "\u{1F48E}",
  dex_50: "\u{1F52C}",
  dex_100: "\u{1F4DA}",
  regional_kanto: "\u{1F3D4}\uFE0F",
  regional_johto: "\u{1F3EF}",
  master_fire: "\u{1F525}",
  master_water: "\u{1F4A7}",
  master_grass: "\u{1F33F}",
  master_electric: "\u26A1",
  master_eevee: "\u{1F98A}",
  master_chikorita: "\u{1F343}",
  master_cyndaquil: "\u{1F994}",
  master_totodile: "\u{1F40A}"
};
var BADGE_ORDER = [
  "hatch",
  "first_evolution",
  "first_shiny",
  "champion",
  "centurion",
  "constellation",
  "master_pokedex",
  "master_fire",
  "master_water",
  "master_grass",
  "master_electric",
  "master_eevee",
  "master_chikorita",
  "master_cyndaquil",
  "master_totodile"
];
function renderBadges(ctx) {
  const { state, locale } = ctx;
  let out = bashPrintf(`
  %s%s${t(locale, "badges.title")}%s

`, BOLD, GOLD, RESET);
  const badges = Array.isArray(state.badges) ? state.badges : [];
  for (const id of BADGE_ORDER) {
    const earnedAt = badges.find((b) => b && b.id === id)?.earned_at ?? "";
    const emoji = BADGE_EMOJI[id] ?? "?";
    const label = t(locale, `badges.${id}.0`);
    const desc = t(locale, `badges.${id}.1`);
    if (earnedAt) {
      out += bashPrintf("   %s  %s%-22s%s  %s%s%s\n     %s%s%s\n", emoji, BOLD, label, RESET, GOLD, String(earnedAt).slice(0, 10), RESET, DIM, desc, RESET);
    } else {
      out += bashPrintf("   %s%s  %-22s%s\n     %s%s%s\n", DIM, "\u25A2", label, RESET, DIM, desc, RESET);
    }
  }
  out += "\n";
  return out;
}
function renderInventory(ctx) {
  const { state, data, locale } = ctx;
  let out = bashPrintf(`
  %s%s${t(locale, "inventory.title")}%s

`, BOLD, GOLD, RESET);
  const items = state.items && typeof state.items === "object" ? state.items : {};
  const entries = Object.entries(items);
  if (entries.length === 0) {
    out += bashPrintf(`  %s${t(locale, "inventory.empty")}%s

`, DIM, RESET);
  } else {
    for (const [itemId, qty] of entries) {
      const meta = data.items?.[itemId];
      const name = meta?.name ?? itemId;
      const emoji = meta?.emoji ?? "?";
      const desc = meta?.desc ?? "";
      out += bashPrintf("   %s  %s%-18s%s  %s\xD7%d%s\n     %s%s%s\n", emoji, BOLD, name, RESET, DIM, Number(qty), RESET, DIM, desc, RESET);
    }
    out += "\n";
  }
  const eeveeForm = state.eevee_form ?? "";
  if (eeveeForm) {
    const stages = data.lineages?.eevee?.stages ?? [];
    const formName = stages.find((s) => s && s.showdown_id === eeveeForm)?.name;
    const msg = t(locale, "inventory.eevee_form", formName);
    out += bashPrintf("  %s%s%s\n\n", DIM, msg, RESET);
  }
  return out;
}
function renderRoster(ctx, field, title) {
  const { state, data } = ctx;
  let out = bashPrintf("\n  %s%s%s%s\n\n", BOLD, GOLD, title, RESET);
  const list = Array.isArray(state[field]) ? state[field] : [];
  if (list.length === 0) {
    out += bashPrintf(`  %s${t(ctx.locale, "team.empty")}%s

`, DIM, RESET);
    return out;
  }
  let i = 0;
  for (const e of list) {
    const lin = jqStr(e.lineage);
    const star = e.is_shiny === true ? `${GOLD}\u2605${RESET} ` : "";
    const name = jqStr(e.max_stage);
    const lvl = Number(e.level);
    const label = data.lineages?.[lin]?.label ?? lin;
    const created = jqStr(e.created_at).slice(0, 10);
    const completed = jqStr(e.completed_at).slice(0, 10);
    out += bashPrintf("   %s[%d]%s  %s%-22s  %sLv.%d%s  %s%s%s  (%s%s%s \u2192 %s%s%s)\n", BOLD, i, RESET, star, name, BOLD, lvl, RESET, DIM, label, RESET, DIM, created, RESET, DIM, completed, RESET);
    i++;
  }
  out += "\n";
  return out;
}
function renderTeam(ctx) {
  let out = renderRoster(ctx, "team", t(ctx.locale, "team.title"));
  const pcCount = Array.isArray(ctx.state.pc_storage) ? ctx.state.pc_storage.length : 0;
  if (pcCount > 0) {
    out += bashPrintf(`  %s${t(ctx.locale, "team.pc_overflow")} \u2014 %sbash %s pc%s

`, DIM, pcCount, DIM, ctx.scriptName, RESET);
  }
  return out;
}
function renderPc(ctx) {
  return renderRoster(ctx, "pc_storage", t(ctx.locale, "pc.title"));
}
var LINEAGE_EMOJI = {
  fire: "\u{1F525}",
  water: "\u{1F4A7}",
  grass: "\u{1F33F}",
  electric: "\u26A1",
  eevee: "\u{1F98A}",
  chikorita: "\u{1F331}",
  cyndaquil: "\u{1F994}",
  totodile: "\u{1F40A}"
};
function lineageEmoji(lineage) {
  return LINEAGE_EMOJI[lineage] ?? "\u2753";
}
function stripAnsiStr(s) {
  return s.replace(/\x1b\[[0-9;]*[a-zA-Z]/g, "");
}
function boxTop(title, width) {
  let titleVisible = 0;
  if (title)
    titleVisible = [...stripAnsiStr(title)].length + 2;
  let dashCount = width - titleVisible - 2;
  if (dashCount < 4)
    dashCount = 4;
  const dashes = "\u2500".repeat(dashCount);
  if (title)
    return `${DIM}\u256D\u2500 ${BOLD}${title}${RESET} ${dashes}\u256E${RESET}
`;
  return `${DIM}\u256D${dashes}\u2500\u2500\u256E${RESET}
`;
}
function boxBottom(width) {
  return `${DIM}\u2570${"\u2500".repeat(width - 2)}\u256F${RESET}
`;
}
function resolveStageDefault(data, lineage, level) {
  const stages = data.lineages?.[lineage]?.stages ?? [];
  const n = Number(level);
  if (level === null || level === void 0 || level === "" || !Number.isFinite(n))
    return null;
  const candidates = stages.filter((s) => s.min_level <= n);
  if (candidates.length === 0)
    return null;
  const maxLvl = Math.max(...candidates.map((s) => s.min_level));
  return stages.find((s) => s.min_level === maxLvl) ?? null;
}
function eeveeFormStage(data, form) {
  const stages = data.lineages?.eevee?.stages ?? [];
  return stages.find((s) => s.showdown_id === form) ?? null;
}
function evoField(data, state, lineage, level, field) {
  const n = Number(level);
  const valid = level !== null && level !== void 0 && level !== "" && Number.isFinite(n);
  if (lineage === "eevee" && valid && n >= 30) {
    const form = state.eevee_form;
    if (form) {
      const st2 = eeveeFormStage(data, form);
      return jqStr(st2 ? st2[field] : null);
    }
  }
  const st = resolveStageDefault(data, lineage, level);
  return jqStr(st ? st[field] : null);
}
function stageFieldWithFallback(data, state, lineage, level, read) {
  let value = "";
  if (lineage === "eevee" && level >= 30) {
    const form = state.eevee_form;
    if (form) {
      const st = eeveeFormStage(data, form);
      if (st)
        value = read(st);
    }
  }
  if (value === "") {
    const st = resolveStageDefault(data, lineage, level);
    if (st)
      value = read(st);
  }
  return value;
}
function progressBar(pct, width = 20) {
  let filled = Math.floor(pct * width / 100);
  if (filled > width)
    filled = width;
  return "\u2588".repeat(filled) + "\u2591".repeat(width - filled);
}
function renderRebalanceNotice(ctx, totalXp) {
  if (totalXp < 1e3)
    return "";
  if (ctx.state.xp_rebalance_v2_acknowledged === true)
    return "";
  const { locale } = ctx;
  let out = "\n";
  out += boxTop(t(locale, "main.xp_rebalance_title"), 70);
  out += bashPrintf("  %s\n", t(locale, "main.xp_rebalance_line1"));
  out += bashPrintf("  %s\n", t(locale, "main.xp_rebalance_line2"));
  out += bashPrintf("  %s\n", t(locale, "main.xp_rebalance_line3"));
  out += bashPrintf("  %s\n", t(locale, "main.xp_rebalance_line4"));
  out += bashPrintf("\n  %s%s%s\n", DIM, t(locale, "main.xp_rebalance_footer"), RESET);
  out += boxBottom(70);
  out += "\n";
  return out;
}
function renderMain(ctx) {
  const { state, data, locale } = ctx;
  const thresholds = data.thresholds ?? [];
  const threshold = (lvl) => thresholds[lvl];
  const maxLevel = thresholds.length - 1;
  const lineage = state.lineage ?? "fire";
  const level = Number(state.current_level);
  const totalXp = Number(state.total_xp);
  const isShiny = state.is_shiny === true;
  const createdAt = jqStr(state.created_at);
  let out = "";
  out += renderRebalanceNotice(ctx, totalXp);
  const name = evoField(data, state, lineage, level, "name");
  const emoji = evoField(data, state, lineage, level, "emoji");
  const lineageLabel = data.lineages?.[lineage]?.label ?? "null";
  const curStage = resolveStageDefault(data, lineage, level);
  const curStageLvl = curStage ? Number(curStage.min_level) : 0;
  const stages = data.lineages?.[lineage]?.stages ?? [];
  const nextStages = stages.filter((s) => s.min_level > level);
  const nextLvl = nextStages.length === 0 ? null : Math.min(...nextStages.map((s) => Number(s.min_level)));
  out += "\n";
  out += boxTop(t(locale, "main.companion"), 64);
  if (ctx.sprite && ctx.sprite.length > 0) {
    for (const line of ctx.sprite)
      out += `  ${line}
`;
    out += "\n";
  }
  const shinyBadge = isShiny ? `${GOLD}\u2605 SHINY${RESET}  ` : "";
  out += bashPrintf(`  %s%s${t(locale, "main.companion")}%s   %s%s%s%s   %sdepuis %s%s

`, BOLD, "", RESET, shinyBadge, DIM, lineageLabel, RESET, DIM, createdAt.slice(0, 10), RESET);
  if (level >= maxLevel) {
    out += bashPrintf("  %s   %s%s%s   %s%sLv.%d%s   %sLv.MAX \u2726%s\n\n", emoji, name, RESET, RESET, "", BOLD, level, RESET, BOLD, RESET);
  } else if (nextLvl === null) {
    const curThreshold = threshold(curStageLvl);
    const nextThreshold = threshold(maxLevel);
    const bandTotal = nextThreshold - curThreshold;
    const remaining = nextThreshold - totalXp;
    let pct = Math.floor((totalXp - curThreshold) * 100 / bandTotal);
    pct = Math.max(0, Math.min(100, pct));
    out += bashPrintf("  %s   %s%s%s%s   %s%sLv.%d%s\n\n", emoji, "", BOLD, name, RESET, "", BOLD, level, RESET);
    out += bashPrintf("  %s%s%s   %s%d%% vers Lv.MAX (forme stable)%s\n\n", "", progressBar(pct), RESET, DIM, pct, RESET);
    out += bashPrintf(`  %s${tPad(locale, "main.xp_total", 22)}%s :  %s tokens
`, DIM, RESET, fmtInt(totalXp));
    out += bashPrintf(`  %s${tPad(locale, "main.remaining", 22)}%s :  %s tokens (Lv.%d)

`, DIM, RESET, fmtInt(remaining), maxLevel);
  } else {
    const curThreshold = threshold(curStageLvl);
    const nextThreshold = threshold(nextLvl);
    const bandXp = totalXp - curThreshold;
    const bandTotal = nextThreshold - curThreshold;
    const remaining = nextThreshold - totalXp;
    let pct = Math.floor(bandXp * 100 / bandTotal);
    pct = Math.max(0, Math.min(100, pct));
    const nextStage = stages.filter((s) => s.min_level > level).sort((a, b) => a.min_level - b.min_level)[0];
    const nextName = jqStr(nextStage?.name);
    const nextEmoji = jqStr(nextStage?.emoji);
    out += bashPrintf("  %s   %s%s%s%s   %s%sLv.%d%s\n\n", emoji, "", BOLD, name, RESET, "", BOLD, level, RESET);
    out += bashPrintf("  %s%s%s   %s%d%% vers %s %s%s\n\n", "", progressBar(pct), RESET, DIM, pct, nextEmoji, nextName, RESET);
    out += bashPrintf(`  %s${tPad(locale, "main.xp_total", 22)}%s :  %s tokens
`, DIM, RESET, fmtInt(totalXp));
    out += bashPrintf(`  %s${tPad(locale, "main.stage_progress", 22)}%s :  %s / %s
`, DIM, RESET, fmtInt(bandXp), fmtInt(bandTotal));
    out += bashPrintf(`  %s${tPad(locale, "main.remaining", 22)}%s :  %s tokens (Lv.%d)

`, DIM, RESET, fmtInt(remaining), nextLvl);
  }
  const moves = stageFieldWithFallback(data, state, lineage, level, (s) => {
    const m = s.moves ?? [];
    return m.length === 0 ? "" : m.join(", ");
  });
  if (moves)
    out += bashPrintf(`  %s${tPad(locale, "main.moves", 22)}%s :  %s

`, DIM, RESET, moves);
  const typesStage = (() => {
    if (lineage === "eevee" && level >= 30 && state.eevee_form) {
      const st2 = eeveeFormStage(data, state.eevee_form);
      if (st2 && Array.isArray(st2.types))
        return st2.types;
    }
    const st = resolveStageDefault(data, lineage, level);
    return st && Array.isArray(st.types) ? st.types : [];
  })();
  if (typesStage.length > 0) {
    let line = bashPrintf(`  %s${tPad(locale, "main.types", 22)}%s :  `, DIM, RESET);
    let first = true;
    for (const ty of typesStage) {
      if (!first)
        line += " ";
      line += `${""}[ ${ty} ]${RESET}`;
      first = false;
    }
    out += line + "\n\n";
  }
  const lang = data.language ?? "fr";
  const pokedexEntry = stageFieldWithFallback(data, state, lineage, level, (s) => {
    const v = s[`pokedex_${lang}`];
    return v == null ? "" : String(v);
  });
  if (pokedexEntry) {
    out += bashPrintf(`  %s${tPad(locale, "main.pokedex_entry", 22)}%s :  %s%s%s

`, DIM, RESET, DIM, pokedexEntry, RESET);
  }
  const heldItem = state.held_item ?? "";
  if (heldItem) {
    const meta = data.items?.[heldItem];
    const heldName = meta?.name ?? heldItem;
    const heldEmoji = meta?.emoji ?? "?";
    out += bashPrintf(`  %s${tPad(locale, "main.held_item", 22)}%s :  %s %s

`, DIM, RESET, heldEmoji, heldName);
  }
  const injured = Number(state.injured_ticks_remaining ?? 0);
  if (injured > 0) {
    out += bashPrintf(`  %s${t(locale, "main.status_injured")}%s   %s(${injured} ticks remaining)%s

`, BOLD + "\\033[91m", RESET, DIM, RESET);
  }
  const friendship = Number(state.friendship ?? 0);
  if (friendship > 0) {
    let heart = "\u{1F497}";
    if (friendship >= 100)
      heart = "\u{1F496}";
    if (friendship >= 500)
      heart = "\u{1F49E}";
    out += bashPrintf(`  %s${tPad(locale, "main.friendship", 22)}%s :  %s %s

`, DIM, RESET, heart, friendship);
  }
  const badges = Array.isArray(state.badges) ? state.badges : [];
  if (badges.length > 0) {
    let line = bashPrintf(`  %s${tPad(locale, "main.badges", 22)}%s :  `, DIM, RESET);
    for (const b of badges)
      line += bashPrintf("%s ", BADGE_EMOJI[b.id] ?? "?");
    line += bashPrintf(" %s(%d/%d)%s\n\n", DIM, badges.length, 15, RESET);
    out += line;
  }
  out += boxBottom(64);
  out += "\n";
  const events = Array.isArray(state.recent_events) ? state.recent_events : [];
  if (events.length > 0) {
    out += bashPrintf(`  %s${t(locale, "main.recent_events")}%s
`, BOLD, RESET);
    for (const ev of events.slice(0, 3)) {
      const at = jqStr(ev.at).replace(/T/g, " ");
      const ename = jqStr(ev.name ?? "");
      const eemoji = jqStr(ev.emoji ?? "");
      const eid = jqStr(ev.id ?? "");
      const exp = ev.xp ?? 0;
      const wildName = (id) => {
        const w = (data.wild_pool ?? []).find((p) => p.id === id);
        return jqStr(w?.[`name_${lang}`]);
      };
      const wildEmoji = (id) => {
        const w = (data.wild_pool ?? []).find((p) => p.id === id);
        return jqStr(w?.emoji);
      };
      switch (ev.type) {
        case "berry":
          out += bashPrintf("   \u{1F347} %s%s %s +%s XP   %s%s%s\n", eemoji, RESET, ename, exp, DIM, at, RESET);
          break;
        case "encounter":
          out += bashPrintf("   \u2728 %s %s   %s%s%s\n", wildEmoji(eid), wildName(eid), DIM, at, RESET);
          break;
        case "battle_won":
          out += bashPrintf(`   \u2694\uFE0F  ${t(locale, "battle.won", wildName(eid), exp)}   %s%s%s
`, DIM, at, RESET);
          break;
        case "battle_lost":
          out += bashPrintf(`   \u{1F494} ${t(locale, "battle.lost", wildName(eid))}   %s%s%s
`, DIM, at, RESET);
          break;
        case "item":
          out += bashPrintf("   \u{1F381} %s%s %s obtenu   %s%s%s\n", eemoji, RESET, ename, DIM, at, RESET);
          break;
        case "trade":
          out += bashPrintf(`   \u{1F504} ${t(locale, "trade.title")}: %s   %s%s%s
`, ename, DIM, at, RESET);
          break;
        default:
          out += bashPrintf("   \u2022 %s   %s%s%s\n", jqStr(ev.type), DIM, at, RESET);
      }
    }
    out += "\n";
  }
  const history = Array.isArray(state.evolution_history) ? state.evolution_history : [];
  if (history.length > 0) {
    out += boxTop(t(locale, "main.history"), 64);
    for (const h of history) {
      const lvl = h.level;
      const ename = jqStr(h.name);
      const eat = jqStr(h.evolved_at).replace(/T/g, " ");
      const eshiny = h.is_shiny === true;
      const eemoji = evoField(data, state, lineage, lvl ?? "null", "emoji");
      const star = eshiny ? `${GOLD}\u2605${RESET} ` : "";
      out += bashPrintf("  %sLv.%-3d%s  %s  %s%-22s  %s%s%s\n", DIM, lvl === void 0 ? "null" : lvl, RESET, eemoji, star, ename, DIM, eat, RESET);
    }
    out += "\n";
    out += boxBottom(64);
    out += "\n";
  }
  out += boxTop(`${t(locale, "main.full_chain")} \u2014 ${lineageLabel}`, 64);
  const eeveeFormId = lineage === "eevee" ? state.eevee_form ?? "" : "";
  for (const s of stages) {
    const imin = Number(s.min_level);
    const iname = jqStr(s.name);
    const iemoji = jqStr(s.emoji);
    const ishow = s.showdown_id;
    const ithresh = threshold(imin);
    let marker;
    let style;
    if (eeveeFormId && imin === 30) {
      if (ishow === eeveeFormId) {
        marker = `${BOLD}\u25BA${RESET}`;
        style = "";
      } else {
        marker = " ";
        style = DIM;
      }
    } else if (imin < curStageLvl) {
      marker = `${BOLD}\u2713${RESET}`;
      style = DIM;
    } else if (imin === curStageLvl) {
      marker = `${BOLD}\u25BA${RESET}`;
      style = "";
    } else {
      marker = " ";
      style = DIM;
    }
    out += bashPrintf("   %s  %sLv.%-3d%s  %s  %s%-22s%s  %s%s tokens%s\n", marker, style, imin, RESET, iemoji, style, iname, RESET, DIM, fmtInt(ithresh), RESET);
  }
  out += boxBottom(64);
  out += "\n";
  out += bashPrintf(`  %s${tPad(locale, "common.subcommands", 22)}%s : team, pc, pokedex, stats, badges, switch, hatch, deposit, withdraw, give, take, trade, reset, --shiny
`, DIM, RESET);
  out += bashPrintf(`  %s${tPad(locale, "common.example", 22)}%s : %sbash ~/.claude/pokemon-status.sh team%s

`, DIM, RESET, DIM, RESET);
  return out;
}
function renderRecap(ctx, scope = "session") {
  const { state, data, locale } = ctx;
  let out = bashPrintf(`
  %s%s${t(locale, "recap.title")}%s

`, BOLD, GOLD, RESET);
  const sessions = state.sessions ?? {};
  const activeSid = () => {
    const entries = Object.entries(sessions);
    if (entries.length === 0)
      return "";
    entries.sort((a, b) => {
      const la = a[1].last_seen ?? "";
      const lb = b[1].last_seen ?? "";
      return la < lb ? -1 : la > lb ? 1 : 0;
    });
    return entries[entries.length - 1][0];
  };
  let sinceIso;
  let label;
  let sid = "";
  if (scope === "today") {
    const now = ctx.nowEpoch ?? 0;
    sinceIso = new Date(now * 1e3).toISOString().slice(0, 10) + "T00:00:00Z";
    label = t(locale, "recap.scope_today");
  } else if (scope === "session" || scope === "") {
    sid = activeSid();
    if (!sid || sid === "null") {
      out += bashPrintf(`  %s${t(locale, "recap.no_session")}%s

`, DIM, RESET);
      return out;
    }
    sinceIso = jqStr(sessions[sid]?.first_seen);
    label = t(locale, "recap.scope_session");
  } else {
    out += bashPrintf(`  %s${t(locale, "recap.unknown_scope", scope)}%s

`, DIM, RESET);
    return out;
  }
  const nowEpoch = ctx.nowEpoch ?? 0;
  const sinceEpoch = Number.isFinite(Date.parse(sinceIso)) ? Math.floor(Date.parse(sinceIso) / 1e3) : nowEpoch;
  const durMin = Math.floor((nowEpoch - sinceEpoch) / 60);
  const durLabel = durMin < 60 ? `${durMin}min` : `${Math.floor(durMin / 60)}h${bashPrintf("%02d", durMin % 60)}`;
  out += bashPrintf(`  %s${t(locale, "recap.context", label, durLabel)}%s

`, DIM, RESET);
  if (scope === "session" || scope === "") {
    const baseline = sessions[sid]?.baseline ?? null;
    if (baseline !== null) {
      const xpDelta = Number(state.total_xp) - Number(baseline.total_xp);
      const frDelta = Number(state.friendship ?? 0) - Number(baseline.friendship);
      const tokDelta = Number(state.lifetime_stats?.total_tokens) - Number(baseline.lifetime_tokens);
      const lvlNow = Number(state.current_level);
      const lvlThen = Number(baseline.current_level);
      out += bashPrintf(`  %s%s${t(locale, "recap.deltas")}%s
`, BOLD, GOLD, RESET);
      out += bashPrintf(`    %s${tPad(locale, "recap.tokens_consumed", 22)}%s :  %s
`, DIM, RESET, fmtInt(tokDelta));
      out += bashPrintf(`    %s${tPad(locale, "recap.xp_gained", 22)}%s :  +%s
`, DIM, RESET, fmtInt(xpDelta));
      out += bashPrintf(`    %s${tPad(locale, "recap.friendship_gained", 22)}%s :  +%s
`, DIM, RESET, fmtInt(frDelta));
      if (lvlNow > lvlThen) {
        out += bashPrintf(`    %s${tPad(locale, "recap.level_progress", 22)}%s :  Lv.%s \u2192 %sLv.%s%s
`, DIM, RESET, lvlThen, GOLD, lvlNow, RESET);
      } else if (lvlNow === 0) {
        const threshold1 = data.thresholds?.[1] ?? 1;
        const pct = Math.trunc(Number(state.total_xp) / threshold1 * 100);
        out += bashPrintf(`    %s${tPad(locale, "recap.hatch_progress", 22)}%s :  %s%% vers Lv.1
`, DIM, RESET, pct);
      } else {
        out += bashPrintf(`    %s${tPad(locale, "recap.level_stable", 22)}%s :  Lv.%s
`, DIM, RESET, lvlNow);
      }
      out += "\n";
    }
  }
  const lang = data.language ?? "fr";
  const wildName = (id) => {
    const w = (data.wild_pool ?? []).find((p) => p.id === id);
    return w === void 0 ? "" : jqStr(w[`name_${lang}`]);
  };
  const wildEmoji = (id) => {
    const w = (data.wild_pool ?? []).find((p) => p.id === id);
    return w === void 0 ? "" : jqStr(w.emoji);
  };
  const sinceFilter = (v) => typeof v === "string" && v >= sinceIso;
  const allEvents = Array.isArray(state.recent_events) ? state.recent_events : [];
  const events = allEvents.filter((e) => sinceFilter(e.at));
  if (events.length === 0) {
    out += bashPrintf(`  %s${t(locale, "recap.no_events")}%s

`, DIM, RESET);
  } else {
    out += bashPrintf(`  %s%s${t(locale, "recap.events_title", events.length)}%s
`, BOLD, GOLD, RESET);
    for (const ev of events) {
      const timeShort = jqStr(ev.at).slice(11, 16);
      const eid = jqStr(ev.id ?? "");
      const exp = ev.xp ?? 0;
      const ename = jqStr(ev.name ?? "");
      const eemoji = jqStr(ev.emoji ?? "");
      const wlvl = ev.wild_level ?? 0;
      switch (ev.type) {
        case "berry":
          out += bashPrintf("    %s%s%s  \u{1F347} %s%s %s +%s XP\n", DIM, timeShort, RESET, eemoji, RESET, ename, exp);
          break;
        case "encounter":
          out += bashPrintf("    %s%s%s  \u{1F3AF} %s%s %s rencontr\xE9\n", DIM, timeShort, RESET, wildEmoji(eid), RESET, wildName(eid));
          break;
        case "battle_won":
          out += bashPrintf("    %s%s%s  \u2694\uFE0F  %sbattle won%s vs %s Lv.%s (+%s XP)\n", DIM, timeShort, RESET, GOLD, RESET, wildName(eid), wlvl, exp);
          break;
        case "battle_lost":
          out += bashPrintf("    %s%s%s  \u{1F4A2} %sbattle lost%s vs %s Lv.%s\n", DIM, timeShort, RESET, DIM, RESET, wildName(eid), wlvl);
          break;
        case "item":
          out += bashPrintf("    %s%s%s  \u{1F381} %s%s %s obtenu\n", DIM, timeShort, RESET, eemoji, RESET, ename);
          break;
      }
    }
    out += "\n";
  }
  const allEvos = Array.isArray(state.evolution_history) ? state.evolution_history : [];
  const evos = allEvos.filter((e) => sinceFilter(e.evolved_at));
  if (evos.length > 0) {
    out += bashPrintf(`  %s%s${t(locale, "recap.evolutions_title")}%s
`, BOLD, GOLD, RESET);
    for (const ev of evos) {
      out += bashPrintf("    %s%s%s  \u2728 Lv.%s \u2014 %s%s%s\n", DIM, jqStr(ev.evolved_at).slice(11, 16), RESET, jqStr(ev.level), BOLD, jqStr(ev.name), RESET);
    }
    out += "\n";
  }
  const allBadges = Array.isArray(state.badges) ? state.badges : [];
  const newBadges = allBadges.filter((b) => sinceFilter(b.earned_at));
  if (newBadges.length > 0) {
    out += bashPrintf(`  %s%s${t(locale, "recap.badges_title")}%s
`, BOLD, GOLD, RESET);
    for (const b of newBadges) {
      out += bashPrintf("    %s%s%s  %s  %s%s%s\n", DIM, jqStr(b.earned_at).slice(11, 16), RESET, BADGE_EMOJI[b.id] ?? "?", BOLD, t(locale, `badges.${b.id}.0`), RESET);
    }
    out += "\n";
  }
  return out;
}
function renderTrainerCard(ctx) {
  const { state, data, locale } = ctx;
  let out = "\n";
  out += boxTop(t(locale, "trainer_card.title"), 64);
  const lineage = state.lineage ?? "fire";
  const level = Number(state.current_level);
  const isShiny = state.is_shiny === true;
  const createdAt = jqStr(state.created_at ?? "\u2014");
  const ls = state.lifetime_stats ?? {};
  const share = data.stats_share ?? {};
  const shareEnabled = share.enabled === true;
  const shareAnon = share.anon_id ?? "";
  const shareName = share.display_name ?? "";
  const lineageLabel = data.lineages?.[lineage]?.label ?? lineage;
  const totalLineages = Object.keys(data.lineages ?? {}).length;
  const stageName = evoField(data, state, lineage, level, "name");
  const stageEmoji = evoField(data, state, lineage, level, "emoji");
  const shinyMark = isShiny ? ` ${GOLD}\u2726${RESET}` : "";
  let label;
  if (shareName && shareAnon)
    label = `${shareName}#${String(shareAnon).slice(0, 4)}`;
  else if (shareAnon)
    label = String(shareAnon);
  else
    label = t(locale, "trainer_card.unnamed");
  out += bashPrintf("\n  %s\u{1F3AE} %s%s%s%s\n", BOLD, GOLD, label, RESET, shinyMark);
  out += bashPrintf(`  %s${t(locale, "trainer_card.trainer_since", createdAt.slice(0, 10))}%s

`, DIM, RESET);
  out += bashPrintf(`  %s${tPad(locale, "trainer_card.companion", 22)}%s :  %s %s%s%s \xB7 Lv.%s
`, DIM, RESET, stageEmoji, BOLD, stageName, RESET, level);
  out += bashPrintf(`  %s${tPad(locale, "trainer_card.lineage", 22)}%s :  %s %s

`, DIM, RESET, lineageEmoji(lineage), lineageLabel);
  out += bashPrintf(`  %s%s${t(locale, "trainer_card.stats_section")}%s
`, BOLD, GOLD, RESET);
  out += bashPrintf(`  %s${tPad(locale, "trainer_card.tokens", 22)}%s :  %s
`, DIM, RESET, fmtInt(ls.total_tokens ?? 0));
  out += bashPrintf(`  %s${tPad(locale, "trainer_card.xp", 22)}%s :  %s
`, DIM, RESET, fmtInt(state.total_xp));
  out += bashPrintf(`  %s${tPad(locale, "trainer_card.friendship", 22)}%s :  %s
`, DIM, RESET, fmtInt(state.friendship ?? 0));
  out += bashPrintf(`  %s${tPad(locale, "trainer_card.shinies", 22)}%s :  %s
`, DIM, RESET, Number(ls.total_shinies ?? 0));
  out += bashPrintf(`  %s${tPad(locale, "trainer_card.lineages_done", 22)}%s :  %s / %s
`, DIM, RESET, Array.isArray(ls.lineages_completed) ? ls.lineages_completed.length : 0, totalLineages);
  out += bashPrintf(`  %s${tPad(locale, "trainer_card.games", 22)}%s :  %s / %s
`, DIM, RESET, Number(ls.games_won ?? 0), Number(ls.games_played ?? 0));
  out += bashPrintf(`  %s${tPad(locale, "trainer_card.pokedex", 22)}%s :  %s / 251

`, DIM, RESET, Object.keys(state.pokedex_wild ?? {}).length);
  const badges = Array.isArray(state.badges) ? state.badges : [];
  if (badges.length > 0) {
    out += bashPrintf(`  %s%s${t(locale, "trainer_card.badges_section", badges.length)}%s
`, BOLD, GOLD, RESET);
    for (const b of badges) {
      out += bashPrintf("  %s \xB7 %s\n", BADGE_EMOJI[b.id] ?? "?", t(locale, `badges.${b.id}.0`));
    }
    out += "\n";
  }
  out += bashPrintf(`  %s%s${t(locale, "trainer_card.share_section")}%s
`, BOLD, GOLD, RESET);
  if (shareEnabled) {
    out += bashPrintf(`  %s${t(locale, "trainer_card.share_active", shareAnon)}%s
`, DIM, RESET);
    if (shareName)
      out += bashPrintf(`  %s${t(locale, "trainer_card.share_pseudo", shareName)}%s
`, DIM, RESET);
  } else {
    out += bashPrintf(`  %s${t(locale, "trainer_card.share_inactive")}%s
`, DIM, RESET);
  }
  out += bashPrintf(`  %s${t(locale, "trainer_card.arena_soon")}%s
`, DIM, RESET);
  out += boxBottom(64);
  out += "\n";
  return out;
}
function renderStats(ctx) {
  const { state, data, locale } = ctx;
  const ls = state.lifetime_stats ?? {};
  let out = bashPrintf(`
  %s%s${t(locale, "stats.title")}%s

`, BOLD, GOLD, RESET);
  const shinies = Number(ls.total_shinies ?? 0);
  const completed = Array.isArray(ls.lineages_completed) ? ls.lineages_completed.length : 0;
  const totalLineages = Object.keys(data.lineages ?? {}).length;
  const firstShiny = ls.first_shiny_at ?? "\u2014";
  out += bashPrintf(`  %s${tPad(locale, "stats.total_tokens", 22)}%s :  %s
`, DIM, RESET, fmtInt(ls.total_tokens));
  out += bashPrintf(`  %s${tPad(locale, "stats.total_evolutions", 22)}%s :  %s
`, DIM, RESET, fmtInt(ls.total_evolutions));
  out += bashPrintf(`  %s${tPad(locale, "stats.total_shinies", 22)}%s :  %s
`, DIM, RESET, fmtInt(shinies));
  out += bashPrintf(`  %s${tPad(locale, "stats.max_level", 22)}%s :  Lv.%s
`, DIM, RESET, jqStr(ls.max_level));
  out += bashPrintf(`  %s${tPad(locale, "stats.total_compagnons", 22)}%s :  %s
`, DIM, RESET, fmtInt(ls.total_compagnons));
  out += bashPrintf(`  %s${tPad(locale, "stats.lineages_completed", 22)}%s :  %s / %s
`, DIM, RESET, completed, totalLineages);
  out += bashPrintf(`  %s${tPad(locale, "stats.first_shiny", 22)}%s :  %s

`, DIM, RESET, String(firstShiny).slice(0, 10));
  const mults = state.last_xp_multipliers;
  if (mults != null) {
    out += bashPrintf(`  %s%s${t(locale, "stats.multipliers_title")}%s

`, BOLD, GOLD, RESET);
    const ctxM = mults.context;
    const tm = mults.type_match;
    const db = mults.daily_bonus;
    const st = mults.status;
    out += bashPrintf(`  %s${tPad(locale, "stats.context", 22)}%s : \xD7%s
`, DIM, RESET, ctxM);
    out += bashPrintf(`  %s${tPad(locale, "stats.type_match", 22)}%s : \xD7%s
`, DIM, RESET, tm);
    out += bashPrintf(`  %s${tPad(locale, "stats.daily_bonus", 22)}%s : \xD7%s
`, DIM, RESET, db);
    out += bashPrintf(`  %s${tPad(locale, "stats.status", 22)}%s : \xD7%s
`, DIM, RESET, st);
    const combined = (Number(ctxM) * Number(tm) * Number(db) * Number(st)).toFixed(2);
    out += bashPrintf(`  %s${tPad(locale, "stats.combined", 22)}%s : %s\xD7%s%s

`, DIM, RESET, BOLD, combined, RESET);
  }
  const status = state.status ?? "ok";
  const streak = Number(state.high_context_streak ?? 0);
  if (status === "tired") {
    out += bashPrintf(`  %s${t(locale, "stats.tired_warning", streak)}%s

`, BOLD, RESET);
  }
  if (shinies > 0) {
    out += bashPrintf(`  %s${t(locale, "stats.shiny_charm")}%s

`, GOLD, RESET);
  }
  return out;
}
function renderPokedex(ctx) {
  const { state, data, locale } = ctx;
  let out = bashPrintf(`
  %s%s${t(locale, "pokedex.title_lineages")}%s

`, BOLD, GOLD, RESET);
  const dex = state.pokedex ?? {};
  for (const [lin, info] of Object.entries(data.lineages ?? {})) {
    const label = info.label;
    const entry = dex[lin] ?? {};
    const seen = entry.seen ?? false;
    const shiny = entry.shiny_seen ?? false;
    const count = Number(entry.count ?? 0);
    const shinyCount = Number(entry.shiny_count ?? 0);
    if (seen === true) {
      const shinyStr = shiny === true ? `  ${GOLD}${t(locale, "pokedex.shiny_seen")}${RESET}` : "";
      out += bashPrintf("   %s\u2713%s  %-20s %s\xD7%d   %s: %d%s\n", BOLD, RESET, label, DIM, count, t(locale, "pokedex.shinies"), shinyCount, shinyStr);
    } else {
      out += bashPrintf("   \u25A2  %s%-20s%s  %s\u2014%s\n", DIM, label, RESET, DIM, RESET);
    }
  }
  const wild = state.pokedex_wild ?? {};
  const wildSeen = Object.keys(wild).length;
  const pool = Array.isArray(data.wild_pool) ? data.wild_pool : [];
  const totalWild = pool.length;
  const lang = data.language ?? "fr";
  out += bashPrintf(`
  %s%s${t(locale, "pokedex.title_wild")}%s   %s(%d / %d)%s

`, BOLD, GOLD, RESET, DIM, wildSeen, totalWild, RESET);
  const sorted = [...pool].sort((a, b) => Number(a.national_dex) - Number(b.national_dex));
  let col = 0;
  for (const w of sorted) {
    const id = w.id;
    const seen = Object.prototype.hasOwnProperty.call(wild, id);
    const marker = seen ? `${BOLD}\u2713${RESET}` : `${DIM}\u25A2${RESET}`;
    const style = seen ? "" : DIM;
    const nameDisp = seen ? jqStr(w[`name_${lang}`]) : "???";
    const rarity = w.rarity ?? "common";
    const rarityMarker = rarity === "legendary" ? `${GOLD}\u2605${RESET}` : " ";
    out += bashPrintf("  %s #%03d %s %s%s%s", marker, Number(w.national_dex), rarityMarker, style, padChars(nameDisp, 12), RESET);
    col++;
    if (col >= 4) {
      out += "\n";
      col = 0;
    }
  }
  if (col > 0)
    out += "\n";
  out += "\n";
  return out;
}

// dist/render/index.js
var RENDERERS = {
  badges: renderBadges,
  inventory: renderInventory,
  team: renderTeam,
  pc: renderPc,
  stats: renderStats,
  pokedex: renderPokedex,
  main: renderMain,
  "trainer-card": renderTrainerCard,
  recap: (ctx, input) => renderRecap(ctx, input.scope ?? "session")
};
var SUPPORTED_VIEWS = Object.keys(RENDERERS);
function renderView(input) {
  const renderer = RENDERERS[input.view];
  if (!renderer)
    return { supported: false, output: "" };
  const ctx = {
    state: input.state,
    data: input.data,
    locale: input.locale,
    lang: input.lang ?? "fr",
    scriptName: input.scriptName ?? "pokemon-status.sh",
    nowEpoch: input.nowEpoch,
    sprite: input.sprite
  };
  return { supported: true, output: renderer(ctx, input) };
}

// dist/xp.js
function thresholdFor(thresholds, level) {
  return thresholds[level];
}
function levelFromXp(thresholds, totalXp) {
  let count = 0;
  for (const t2 of thresholds)
    if (t2 <= totalXp)
      count++;
  return count - 1;
}
function xpToNext(thresholds, totalXp, level) {
  const maxLevel = thresholds.length - 1;
  if (level >= maxLevel)
    return 0;
  return thresholds[level + 1] - totalXp;
}
function progressPct(thresholds, totalXp, level) {
  const maxLevel = thresholds.length - 1;
  if (level >= maxLevel)
    return 100;
  const cur = thresholds[level];
  const nxt = thresholds[level + 1];
  const pct = Math.floor((totalXp - cur) * 100 / (nxt - cur));
  if (pct < 0)
    return 0;
  if (pct > 100)
    return 100;
  return pct;
}
function xpMultiplier(usedPct) {
  if (usedPct == null)
    return 1;
  const p = Math.round(usedPct);
  if (p <= 25)
    return 2;
  if (p <= 50)
    return 1.5;
  if (p <= 75)
    return 1;
  return 0.5;
}
function typeMatchMultiplier(lineage, usedPct) {
  const p = Math.round(usedPct);
  switch (lineage) {
    case "fire":
      return p < 30 ? 1.2 : 1;
    case "water":
      return p > 70 ? 1.2 : 1;
    case "grass":
      return p >= 40 && p <= 60 ? 1.2 : 1;
    case "electric":
      return 1.2;
    case "eevee":
      return 1.1;
    default:
      return 1;
  }
}

// dist/collection.js
function clone(v) {
  return JSON.parse(JSON.stringify(v));
}
function removeAt(arr, idx) {
  return [...arr.slice(0, idx), ...arr.slice(idx + 1)];
}
function lastStageName(state) {
  const hist = Array.isArray(state.evolution_history) ? state.evolution_history : [];
  const name = hist.length ? hist[hist.length - 1]?.name : void 0;
  return name ?? "\u0152uf";
}
function activeToArchive(state, now) {
  if (state.lineage == null)
    return clone(state);
  const s = clone(state);
  const lin = s.lineage;
  s.team = Array.isArray(s.team) ? s.team : [];
  s.team.push({
    lineage: s.lineage,
    is_shiny: s.is_shiny,
    level: s.current_level,
    total_xp: s.total_xp,
    max_stage: lastStageName(s),
    evolution_history: s.evolution_history,
    eevee_form: s.eevee_form,
    items: s.items,
    created_at: s.created_at,
    completed_at: now
  });
  if (s.team.length > 6) {
    s.pc_storage = Array.isArray(s.pc_storage) ? s.pc_storage : [];
    s.pc_storage.push(s.team[0]);
    s.team = s.team.slice(1);
  }
  s.lifetime_stats = s.lifetime_stats ?? {};
  if (s.current_level >= 100) {
    s.lifetime_stats.total_compagnons = (s.lifetime_stats.total_compagnons ?? 0) + 1;
  }
  const completed = Array.isArray(s.lifetime_stats.lineages_completed) ? s.lifetime_stats.lineages_completed : [];
  if (completed.indexOf(lin) === -1 && s.current_level >= 100) {
    s.lifetime_stats.lineages_completed = [...completed, lin];
  }
  return s;
}
function resetActive(state, now, forcedLineage) {
  const s = clone(state);
  s.lineage = forcedLineage != null && forcedLineage !== "" ? forcedLineage : null;
  s.is_shiny = false;
  s.current_level = 0;
  s.total_xp = 0;
  s.evolution_history = [];
  s.evolution_flash_remaining = 10;
  s.created_at = now;
  s.eevee_form = null;
  s.items = {};
  return s;
}
function archiveToTeam(state, now) {
  return resetActive(activeToArchive(state, now), now);
}
function loadEntryToActive(s, entry, now) {
  s.lineage = entry.lineage;
  s.is_shiny = entry.is_shiny;
  s.current_level = entry.level;
  s.total_xp = entry.total_xp;
  s.evolution_history = entry.evolution_history ?? [];
  s.eevee_form = entry.eevee_form;
  s.items = entry.items ?? {};
  s.created_at = entry.created_at;
  s.last_updated = now;
  s.evolution_flash_remaining = 3;
}
function loadTeamToActive(state, now, idx) {
  const s = clone(state);
  const entry = s.team[idx];
  loadEntryToActive(s, entry, now);
  s.team = removeAt(s.team, idx);
  return s;
}
function teamToPc(state, idx) {
  const s = clone(state);
  s.pc_storage = Array.isArray(s.pc_storage) ? s.pc_storage : [];
  s.pc_storage.push(s.team[idx]);
  s.team = removeAt(s.team, idx);
  return s;
}
function pcToTeamOrActive(state, now, idx) {
  const activeEmpty = state.lineage == null || state.current_level === 0;
  const teamFull = (Array.isArray(state.team) ? state.team.length : 0) >= 6;
  const s = clone(state);
  if (activeEmpty) {
    loadEntryToActive(s, s.pc_storage[idx], now);
    s.pc_storage = removeAt(s.pc_storage, idx);
    return s;
  }
  if (!teamFull) {
    s.team = Array.isArray(s.team) ? s.team : [];
    s.team.push(s.pc_storage[idx]);
    s.pc_storage = removeAt(s.pc_storage, idx);
    return s;
  }
  return null;
}
function releaseSlot(state, area, idx) {
  const s = clone(state);
  if (area === "team")
    s.team = removeAt(s.team, idx);
  else if (area === "pc")
    s.pc_storage = removeAt(s.pc_storage, idx);
  return s;
}
function checkBadges(state, now, data) {
  const s = clone(state);
  s.badges = Array.isArray(s.badges) ? s.badges : [];
  const add = (id) => {
    if (!s.badges.some((b) => b && b.id === id))
      s.badges.push({ id, earned_at: now });
  };
  const ls = s.lifetime_stats ?? {};
  const hist = Array.isArray(s.evolution_history) ? s.evolution_history : [];
  const wildSeen = Object.keys(s.pokedex_wild ?? {});
  const wildCount = wildSeen.length;
  const pool = Array.isArray(data?.wild_pool) ? data.wild_pool : [];
  const kanto = pool.filter((w) => w.national_dex >= 1 && w.national_dex <= 151).map((w) => w.id);
  const johto = pool.filter((w) => w.national_dex >= 152 && w.national_dex <= 251).map((w) => w.id);
  const hasAllOf = (ids) => ids.length > 0 && ids.every((id) => wildSeen.includes(id));
  const completed = Array.isArray(ls.lineages_completed) ? ls.lineages_completed : [];
  const pokedexSeen = Object.values(s.pokedex ?? {}).filter((v) => v && v.seen).length;
  if (hist.some((e) => e.level === 1))
    add("hatch");
  if (hist.some((e) => e.level >= 16))
    add("first_evolution");
  if ((ls.total_shinies ?? 0) > 0)
    add("first_shiny");
  if ((ls.max_level ?? 0) >= 100)
    add("champion");
  if ((ls.total_tokens ?? 0) >= 1e8)
    add("centurion");
  if ((ls.total_shinies ?? 0) >= 5)
    add("constellation");
  if (pokedexSeen >= 5)
    add("master_pokedex");
  if (wildCount >= 50)
    add("dex_50");
  if (wildCount >= 100)
    add("dex_100");
  if (hasAllOf(kanto))
    add("regional_kanto");
  if (hasAllOf(johto))
    add("regional_johto");
  for (const lin of ["fire", "water", "grass", "electric", "eevee", "chikorita", "cyndaquil", "totodile"]) {
    if (completed.includes(lin))
      add(`master_${lin}`);
  }
  return s;
}
function switchCompanion(state, now, slot) {
  return loadTeamToActive(activeToArchive(state, now), now, slot);
}
function hatch(state, now, data, forcedLineage) {
  let s = state;
  if (Number(state.current_level) > 0)
    s = activeToArchive(s, now);
  s = resetActive(s, now, forcedLineage);
  return checkBadges(s, now, data);
}
function ceremonialReset(state, now, data) {
  return checkBadges(archiveToTeam(state, now), now, data);
}

// dist/tick.js
function clone2(v) {
  return JSON.parse(JSON.stringify(v));
}
function prepend10(list, ev) {
  return [ev, ...Array.isArray(list) ? list : []].slice(0, 10);
}
function tick(input) {
  const { data, now, now_epoch, session_id: sid, current_tokens, decisions } = input;
  const usedPct = input.used_pct == null ? null : Number(input.used_pct);
  const thresholds = data.thresholds ?? [];
  const maxLevel = thresholds.length - 1;
  const s = clone2(input.state);
  s.badges ??= [];
  s.team ??= [];
  s.pc_storage ??= [];
  s.pokedex ??= {};
  s.lifetime_stats ??= {
    total_tokens: 0,
    total_evolutions: 0,
    total_shinies: 0,
    max_level: 0,
    lineages_completed: [],
    total_compagnons: 1,
    first_shiny_at: null
  };
  const ls = s.lifetime_stats;
  ls.max_level = (ls.max_level ?? 0) > s.current_level ? ls.max_level : s.current_level;
  const linNow = s.lineage ?? "";
  if (linNow !== "" && (s.pokedex[linNow] ?? null) == null) {
    s.pokedex[linNow] = {
      seen: true,
      count: 1,
      first_seen_at: s.created_at,
      shiny_seen: s.is_shiny,
      shiny_count: s.is_shiny ? 1 : 0
    };
  }
  if (linNow !== "" && s.is_shiny === true && (s.pokedex[linNow]?.shiny_seen ?? false) === false) {
    s.pokedex[linNow].shiny_seen = true;
    s.pokedex[linNow].shiny_count = (s.pokedex[linNow].shiny_count ?? 0) + 1;
  }
  if (s.is_shiny === true && ls.total_shinies === 0) {
    ls.total_shinies = 1;
    ls.first_shiny_at ??= s.created_at;
  }
  let lineage = s.lineage ?? "";
  if (!lineage) {
    lineage = decisions.starter;
    s.lineage = lineage;
    s.pokedex[lineage] ??= { seen: false, shiny_seen: false, count: 0, shiny_count: 0, first_seen_at: null };
    s.pokedex[lineage].seen = true;
    s.pokedex[lineage].count += 1;
    s.pokedex[lineage].first_seen_at ??= now;
  }
  const expectedLevel = levelFromXp(thresholds, s.total_xp ?? 0);
  if ((s.current_level ?? 0) > expectedLevel) {
    s.current_level = expectedLevel;
    s.evolution_flash_remaining = 0;
  }
  let isShiny = s.is_shiny;
  const prevLevel = s.current_level;
  s.sessions ??= {};
  s.sessions[sid] ??= {};
  const sess = s.sessions[sid];
  const prevTokens = sess.last_tick_tokens ?? sess.max_context_tokens ?? 0;
  const rawDelta = current_tokens > prevTokens ? current_tokens - prevTokens : 0;
  let pending = (sess.pending_tokens ?? 0) + rawDelta;
  const lastCreditAt = sess.last_xp_credit_at ?? 0;
  const gapS = now_epoch - lastCreditAt;
  let delta = 0;
  const TICK_CAP = 1e4;
  if (gapS >= 30 && pending > 0) {
    delta = pending > TICK_CAP ? TICK_CAP : pending;
    pending -= delta;
    sess.last_xp_credit_at = now_epoch;
  }
  sess.pending_tokens = pending;
  const xpMult = xpMultiplier(usedPct);
  const typeMatch = typeMatchMultiplier(lineage, usedPct == null ? 50 : usedPct);
  const today = now.slice(0, 10);
  let dailyMult = 1;
  if ((s.last_daily_bonus_date ?? "") !== today) {
    dailyMult = 1.5;
    s.last_daily_bonus_date = today;
  }
  const pctInt = Math.round(usedPct ?? 0);
  if (pctInt >= 90)
    s.high_context_streak = (s.high_context_streak ?? 0) + 1;
  else
    s.high_context_streak = 0;
  let statusMult = 1;
  if ((s.high_context_streak ?? 0) >= 5) {
    s.status = "tired";
    statusMult = 0.75;
  } else {
    s.status = "ok";
    statusMult = 1;
  }
  const heldItem = s.held_item ?? "";
  let heldMult = 1;
  if (heldItem)
    heldMult = Number(data.items?.[heldItem]?.effect_xp_mult ?? 1);
  const injuredTicks = s.injured_ticks_remaining ?? 0;
  let injuredMult = 1;
  if (injuredTicks > 0) {
    injuredMult = 0.75;
    s.injured_ticks_remaining = injuredTicks - 1;
    if (heldItem === "oran_berry") {
      s.held_item = null;
      s.injured_ticks_remaining = 0;
      injuredMult = 1;
    }
  }
  const shinyHunter = data.shiny_hunter_mode === true;
  const d = new Date(now);
  const curMonth = d.getUTCMonth() + 1;
  const curDay = d.getUTCDate();
  let seasonMult = 1;
  for (const season of Object.values(data.seasons ?? {})) {
    if (curMonth === season.month && curDay >= season.day_start && curDay <= season.day_end) {
      seasonMult = Number(season.boost_mult_xp ?? 1);
      break;
    }
  }
  let weightedDelta = 0;
  if (!shinyHunter) {
    let m = xpMult * typeMatch * dailyMult * statusMult * heldMult * injuredMult * seasonMult;
    if (m > 2)
      m = 2;
    weightedDelta = Math.trunc(delta * m);
  }
  s.last_xp_multipliers = {
    context: xpMult.toFixed(1),
    type_match: typeMatch.toFixed(1),
    daily_bonus: dailyMult.toFixed(1),
    status: statusMult === 0.75 ? "0.75" : "1.0"
  };
  if (decisions.berry.fired) {
    const b = data.berries[decisions.berry.index];
    s.total_xp = (s.total_xp ?? 0) + b.xp_bonus;
    s.recent_events = prepend10(s.recent_events, {
      type: "berry",
      id: b.id,
      name: b.name,
      emoji: b.emoji,
      xp: b.xp_bonus,
      at: now
    });
  }
  if (decisions.encounter.fired) {
    const w = data.wild_pool[decisions.encounter.index];
    s.pokedex_wild ??= {};
    s.pokedex_wild[w.id] = {
      count: (s.pokedex_wild[w.id]?.count ?? 0) + 1,
      first_seen_at: s.pokedex_wild[w.id]?.first_seen_at ?? now,
      last_seen_at: now
    };
    s.recent_events = prepend10(s.recent_events, { type: "encounter", id: w.id, at: now });
    if (decisions.battle.fired) {
      const ownLevel = s.current_level;
      const wildLevel = decisions.battle.wild_level;
      const battleWon = ownLevel >= wildLevel - 3;
      if (battleWon) {
        const bonusXp = Math.trunc(decisions.battle.bonus_xp_raw * wildLevel / 25);
        s.total_xp = (s.total_xp ?? 0) + bonusXp;
        s.recent_events = prepend10(s.recent_events, {
          type: "battle_won",
          id: w.id,
          wild_level: wildLevel,
          xp: bonusXp,
          at: now
        });
      } else {
        s.injured_ticks_remaining = data.battle_injured_ticks ?? 5;
        s.recent_events = prepend10(s.recent_events, {
          type: "battle_lost",
          id: w.id,
          wild_level: wildLevel,
          at: now
        });
      }
    }
    if (decisions.item.fired) {
      const itemKeys = Object.keys(data.items ?? {}).sort();
      const itemId = itemKeys[decisions.item.index];
      s.items ??= {};
      s.items[itemId] = (s.items[itemId] ?? 0) + 1;
      s.recent_events = prepend10(s.recent_events, {
        type: "item",
        id: itemId,
        name: data.items[itemId]?.name,
        emoji: data.items[itemId]?.emoji,
        at: now
      });
    }
  }
  s.total_xp = (s.total_xp ?? 0) + weightedDelta;
  ls.total_tokens = (ls.total_tokens ?? 0) + rawDelta;
  sess.first_seen ??= now;
  sess.last_seen = now;
  sess.max_context_tokens = (sess.max_context_tokens ?? 0) > current_tokens ? sess.max_context_tokens : current_tokens;
  sess.last_tick_tokens = current_tokens;
  s.last_updated = now;
  if (!sess.baseline) {
    sess.baseline = {
      total_xp: s.total_xp - weightedDelta,
      friendship: s.friendship ?? 0,
      lifetime_tokens: ls.total_tokens - rawDelta,
      lineage: s.lineage,
      current_level: s.current_level,
      evolution_count: (s.evolution_history ?? []).length,
      badge_count: (s.badges ?? []).length,
      pokedex_wild_count: Object.keys(s.pokedex_wild ?? {}).length,
      games_won: ls.games_won ?? 0
    };
  }
  const totalXp = s.total_xp;
  const newLevel = levelFromXp(thresholds, totalXp);
  if (newLevel > prevLevel) {
    if (prevLevel === 0 && newLevel >= 1) {
      isShiny = decisions.shiny;
      s.is_shiny = isShiny;
      if (isShiny) {
        s.pokedex[lineage].shiny_seen = true;
        s.pokedex[lineage].shiny_count += 1;
        ls.total_shinies += 1;
        ls.first_shiny_at ??= now;
      }
    }
    if (lineage === "eevee" && prevLevel < 30 && newLevel >= 30) {
      let chosenForm = "";
      let usedStone = "";
      for (const stone of ["fire_stone", "water_stone", "thunder_stone"]) {
        if ((s.items?.[stone] ?? 0) > 0) {
          usedStone = stone;
          chosenForm = data.eevee_evolution_rules[stone];
          break;
        }
      }
      if (!chosenForm) {
        const friendship = s.friendship ?? 0;
        const threshold = data.eevee_friendship_threshold ?? 50;
        const hour = d.getUTCHours();
        if (friendship >= threshold) {
          chosenForm = hour >= 6 && hour < 18 ? data.eevee_evolution_rules.day_default : data.eevee_evolution_rules.night_default;
        } else {
          const fallback = ["fire_stone", "water_stone", "thunder_stone"][decisions.eevee_fallback_index];
          chosenForm = data.eevee_evolution_rules[fallback];
        }
      }
      s.eevee_form = chosenForm;
      if (usedStone) {
        s.items[usedStone] -= 1;
        if (s.items[usedStone] <= 0)
          delete s.items[usedStone];
      }
    }
    const stages = data.lineages?.[lineage]?.stages ?? [];
    const transitions = stages.filter((st) => st.min_level > prevLevel && st.min_level <= newLevel).map((st) => st.min_level);
    let stageChanged = false;
    let transitionCount = 0;
    let eeveeLogged = false;
    for (const t2 of transitions) {
      if (lineage === "eevee" && t2 === 30 && eeveeLogged)
        continue;
      const evoName = evoField(data, s, lineage, t2, "name");
      s.evolution_history = [
        ...s.evolution_history ?? [],
        { level: t2, name: evoName, evolved_at: now, is_shiny: isShiny }
      ];
      stageChanged = true;
      transitionCount += 1;
      if (lineage === "eevee" && t2 === 30)
        eeveeLogged = true;
    }
    if (transitionCount > 0)
      ls.total_evolutions = (ls.total_evolutions ?? 0) + transitionCount;
    ls.max_level = (ls.max_level ?? 0) > newLevel ? ls.max_level : newLevel;
    const flashValue = stageChanged ? 3 : 0;
    s.current_level = newLevel;
    if (flashValue > 0)
      s.evolution_flash_remaining = flashValue;
    if (prevLevel < maxLevel && newLevel >= maxLevel) {
      Object.assign(s, archiveToTeam(s, now));
    }
  } else {
    const flash = s.evolution_flash_remaining ?? 0;
    if (flash > 0)
      s.evolution_flash_remaining = flash - 1;
  }
  s.animation_frame_index = (s.animation_frame_index ?? 0) + 1;
  if (lineage && lineage !== "null")
    s.friendship = (s.friendship ?? 0) + 1;
  Object.assign(s, checkBadges(s, now, data));
  const cutoff = new Date(now_epoch * 1e3 - 30 * 86400 * 1e3).toISOString().replace(/\.\d{3}Z$/, "Z");
  const kept = {};
  for (const [k, v] of Object.entries(s.sessions)) {
    if (k === sid || (v.last_seen ?? "") >= cutoff)
      kept[k] = v;
  }
  s.sessions = kept;
  return { state: s };
}

// dist/render/net.js
var RESET2 = "\x1B[0m";
var BOLD2 = "\x1B[1m";
var DIM2 = "\x1B[2m";
var GOLD2 = "\x1B[33m";
function rankPrefix(rank) {
  if (rank === 1)
    return "\u{1F947}";
  if (rank === 2)
    return "\u{1F948}";
  if (rank === 3)
    return "\u{1F949}";
  return bashPrintf("%2s.", String(rank));
}
function renderLeaderboard(data, locale, metric, result) {
  let out = bashPrintf(`
  %s%s${t(locale, "leaderboard.title", metric)}%s

`, BOLD2, GOLD2, RESET2);
  if ("endpoint" in result) {
    return out + bashPrintf(`  %s${t(locale, "leaderboard.no_endpoint")}%s

`, DIM2, RESET2);
  }
  if ("fetchFailed" in result) {
    return out + bashPrintf(`  %s${t(locale, "leaderboard.fetch_failed")}%s

`, DIM2, RESET2);
  }
  const resp = result.resp;
  const myId = data.stats_share?.anon_id ?? "";
  out += bashPrintf(`  %s${t(locale, "leaderboard.subtitle", resp.total_players)}%s

`, DIM2, RESET2);
  const top = Array.isArray(resp.top) ? resp.top : [];
  top.forEach((e, i) => {
    const rank = i + 1;
    const id = e.anon_id;
    const name = e.display_name ?? "";
    const lin = e.lineage ?? "-";
    const lvl = e.level;
    const isMe = id === myId;
    const mark = isMe ? GOLD2 : DIM2;
    const star = e.is_shiny === true ? `${GOLD2} \u2726${RESET2}` : "";
    const label = name ? `${name}#${String(id).slice(0, 4)}` : String(id);
    const lvlLabel = String(lvl) === "0" ? "\u{1F95A}" : `lv.${lvl}`;
    out += bashPrintf("  %s  %s%-20s%s  %s%14s%s   %s%s %s %s%s%s\n", rankPrefix(rank), BOLD2 + mark, label, RESET2, mark, fmtInt(e.value), RESET2, DIM2, lineageEmoji(lin), lin, lvlLabel, star, RESET2);
  });
  return out + "\n";
}
function renderAggregate(_data, locale, result) {
  let out = bashPrintf(`
  %s%s${t(locale, "aggregate.title")}%s

`, BOLD2, GOLD2, RESET2);
  if ("endpoint" in result) {
    return out + bashPrintf(`  %s${t(locale, "leaderboard.no_endpoint")}%s

`, DIM2, RESET2);
  }
  if ("fetchFailed" in result) {
    return out + bashPrintf(`  %s${t(locale, "leaderboard.fetch_failed")}%s

`, DIM2, RESET2);
  }
  const resp = result.resp;
  const players = resp.total_players;
  if (String(players) === "0" || players == null) {
    return out + bashPrintf(`  %s${t(locale, "aggregate.empty")}%s

`, DIM2, RESET2);
  }
  out += bashPrintf(`  %s${tPad(locale, "aggregate.players", 22)}%s :  %s
`, DIM2, RESET2, fmtInt(players));
  out += bashPrintf(`  %s${tPad(locale, "aggregate.tokens", 22)}%s :  %s
`, DIM2, RESET2, fmtInt(resp.total_tokens_combined));
  out += bashPrintf(`  %s${tPad(locale, "aggregate.shinies", 22)}%s :  %s
`, DIM2, RESET2, fmtInt(resp.total_shinies_observed));
  out += bashPrintf(`  %s${tPad(locale, "aggregate.shiny_rate", 22)}%s :  %s

`, DIM2, RESET2, resp.shiny_rate_observed ?? 0);
  out += bashPrintf(`  %s%s${t(locale, "aggregate.distribution")}%s
`, BOLD2, GOLD2, RESET2);
  const dist = Object.entries(resp.active_lineage_distribution ?? {});
  dist.sort((a, b) => Number(b[1]) - Number(a[1]));
  for (const [lin, count] of dist) {
    out += bashPrintf("    %s %s%-12s%s : %d\n", lineageEmoji(lin), DIM2, lin, RESET2, Number(count));
  }
  return out + "\n";
}

// dist/config.js
var RESET3 = "\x1B[0m";
var BOLD3 = "\x1B[1m";
var DIM3 = "\x1B[2m";
var GOLD3 = "\x1B[33m";
var charLen = (s) => [...s].length;
function ensureShare(data) {
  data.stats_share ??= {};
}
function isClear(action) {
  return action === "clear" || action === "remove" || action === "reset";
}
function runConfig(input) {
  const { cmd, args, locale } = input;
  const data = JSON.parse(JSON.stringify(input.data));
  const L = (k, ...a) => t(locale, k, ...a);
  const action = args[0] ?? "";
  let changed = false;
  const mutate2 = (fn) => {
    ensureShare(data);
    fn();
    changed = true;
  };
  if (cmd === "quote") {
    let out2 = bashPrintf(`
  %s%s${L("quote.title")}%s

`, BOLD3, GOLD3, RESET3);
    const current2 = data.stats_share?.quote ?? "";
    if (action === "") {
      out2 += current2 ? bashPrintf('  %s"%s"%s\n\n', GOLD3, current2, RESET3) : bashPrintf(`  %s${L("quote.unset")}%s

`, DIM3, RESET3);
      out2 += bashPrintf(`  %s${L("quote.usage")}%s

`, DIM3, RESET3);
    } else if (isClear(action)) {
      mutate2(() => {
        data.stats_share.quote = null;
      });
      out2 += bashPrintf(`  %s${L("quote.cleared")}%s

`, DIM3, RESET3);
    } else {
      const text = args.join(" ");
      const len = charLen(text);
      if (len > 80)
        out2 += bashPrintf(`  %s${L("quote.too_long", len)}%s

`, DIM3, RESET3);
      else if (/[\r\n]/.test(text))
        out2 += bashPrintf(`  %s${L("quote.no_newline")}%s

`, DIM3, RESET3);
      else {
        mutate2(() => {
          data.stats_share.quote = text;
        });
        out2 += bashPrintf(`  %s${L("quote.set", text)}%s

`, GOLD3, RESET3);
        out2 += bashPrintf(`  %s${L("quote.set_hint")}%s

`, DIM3, RESET3);
      }
    }
    return { data, output: out2, changed };
  }
  if (cmd === "bio") {
    let out2 = bashPrintf(`
  %s%s${L("bio.title")}%s

`, BOLD3, GOLD3, RESET3);
    const current2 = data.stats_share?.bio ?? "";
    if (action === "") {
      if (current2) {
        for (const line of current2.split("\n"))
          out2 += bashPrintf("  %s%s%s\n", GOLD3, line, RESET3);
        out2 += "\n";
      } else {
        out2 += bashPrintf(`  %s${L("bio.unset")}%s

`, DIM3, RESET3);
      }
      out2 += bashPrintf(`  %s${L("bio.usage")}%s

`, DIM3, RESET3);
    } else if (isClear(action)) {
      mutate2(() => {
        data.stats_share.bio = null;
      });
      out2 += bashPrintf(`  %s${L("bio.cleared")}%s

`, DIM3, RESET3);
    } else {
      const text = args.join("\n");
      const len = charLen(text);
      const lines = text.split("\n").length;
      if (len > 160)
        out2 += bashPrintf(`  %s${L("bio.too_long", len)}%s

`, DIM3, RESET3);
      else if (lines > 4)
        out2 += bashPrintf(`  %s${L("bio.too_many_lines", lines)}%s

`, DIM3, RESET3);
      else {
        mutate2(() => {
          data.stats_share.bio = text;
        });
        out2 += bashPrintf(`  %s${L("bio.set")}%s

`, GOLD3, RESET3);
        out2 += bashPrintf(`  %s${L("bio.set_hint")}%s

`, DIM3, RESET3);
      }
    }
    return { data, output: out2, changed };
  }
  let out = bashPrintf(`
  %s%s${L("pins.title")}%s

`, BOLD3, GOLD3, RESET3);
  const owned = Array.isArray(input.state.badges) ? input.state.badges.map((b) => b.id) : [];
  const current = data.stats_share?.pinned_badges ?? [];
  if (action === "") {
    if (current.length > 0) {
      for (const pin of current)
        out += bashPrintf("  %s\u2605 %s%s\n", GOLD3, pin, RESET3);
      out += "\n";
    } else {
      out += bashPrintf(`  %s${L("pins.unset")}%s

`, DIM3, RESET3);
    }
    out += bashPrintf(`  %s${L("pins.usage")}%s
`, DIM3, RESET3);
    out += bashPrintf(`  %s${L("pins.owned")}%s %s

`, DIM3, RESET3, owned.join(", "));
  } else if (isClear(action)) {
    mutate2(() => {
      data.stats_share.pinned_badges = [];
    });
    out += bashPrintf(`  %s${L("pins.cleared")}%s

`, DIM3, RESET3);
  } else if (action === "set") {
    const pins = args.slice(1).join(" ").replace(/,/g, " ").split(/\s+/).filter(Boolean);
    if (pins.length === 0)
      out += bashPrintf(`  %s${L("pins.empty")}%s

`, DIM3, RESET3);
    else if (pins.length > 3)
      out += bashPrintf(`  %s${L("pins.too_many", pins.length)}%s

`, DIM3, RESET3);
    else {
      const bad = pins.find((p) => !owned.includes(p));
      if (bad !== void 0)
        out += bashPrintf(`  %s${L("pins.not_owned", bad)}%s

`, DIM3, RESET3);
      else {
        mutate2(() => {
          data.stats_share.pinned_badges = pins;
        });
        out += bashPrintf(`  %s${L("pins.set")}%s

`, GOLD3, RESET3);
        out += bashPrintf(`  %s${L("pins.set_hint")}%s

`, DIM3, RESET3);
      }
    }
  } else {
    out += bashPrintf(`  %s${L("pins.usage")}%s

`, DIM3, RESET3);
  }
  return { data, output: out, changed };
}

// dist/share.js
var RESET4 = "\x1B[0m";
var BOLD4 = "\x1B[1m";
var DIM4 = "\x1B[2m";
var GOLD4 = "\x1B[33m";
var NAME_RE = /^[a-zA-Z0-9_-]{2,24}$/;
function buildSubmitPayload(data, state, anonId, clientVer, displayName, now) {
  const share = data.stats_share ?? {};
  const ls = state.lifetime_stats ?? {};
  const orNull = (v) => v === "" ? null : v;
  return {
    anon_id: anonId,
    display_name: orNull(displayName),
    quote: orNull(share.quote ?? ""),
    bio: orNull(share.bio ?? ""),
    pinned_badges: share.pinned_badges ?? [],
    schema_version: 1,
    client_version: clientVer,
    submitted_at: now,
    stats: {
      lifetime: {
        total_tokens: ls.total_tokens ?? 0,
        total_evolutions: ls.total_evolutions ?? 0,
        total_shinies: ls.total_shinies ?? 0,
        max_level: ls.max_level ?? 0,
        total_compagnons: ls.total_compagnons ?? 0,
        lineages_completed: ls.lineages_completed ?? [],
        games_won: ls.games_won ?? 0,
        games_played: ls.games_played ?? 0
      },
      active: {
        lineage: state.lineage ?? null,
        current_level: state.current_level ?? 0,
        is_shiny: state.is_shiny ?? false
      },
      badges: (state.badges ?? []).map((b) => b.id),
      pokedex_seen_count: Object.keys(state.pokedex_wild ?? {}).length,
      pokedex_seen_ids: Object.keys(state.pokedex_wild ?? {})
    }
  };
}
var SHARE_RESET = "\x1B[0m";
var SHARE_BOLD = "\x1B[1m";
var SHARE_DIM = "\x1B[2m";
var SHARE_GOLD = "\x1B[33m";
var shareTitle = (locale) => bashPrintf(`
  %s%s${t(locale, "share.title")}%s

`, SHARE_BOLD, SHARE_GOLD, SHARE_RESET);
function renderForget(data, locale, anonId, ok) {
  const d = JSON.parse(JSON.stringify(data));
  let out = shareTitle(locale);
  let changed = false;
  if (!anonId) {
    out += bashPrintf(`  %s${t(locale, "share.no_id")}%s

`, SHARE_DIM, SHARE_RESET);
  } else if (ok) {
    d.stats_share ??= {};
    d.stats_share.enabled = false;
    d.stats_share.anon_id = null;
    changed = true;
    out += bashPrintf(`  %s${t(locale, "share.forgotten", anonId)}%s

`, SHARE_GOLD, SHARE_RESET);
  } else {
    out += bashPrintf(`  %s${t(locale, "share.forget_failed")}%s

`, SHARE_DIM, SHARE_RESET);
  }
  return { data: d, output: out, changed };
}
function renderSubmit(state, locale, enabled, code, cooldownS, now) {
  const s = JSON.parse(JSON.stringify(state));
  let out = shareTitle(locale);
  let changed = false;
  if (!enabled) {
    out += bashPrintf(`  %s${t(locale, "share.not_enabled")}%s

`, SHARE_DIM, SHARE_RESET);
  } else if (code === 200) {
    s.last_stats_submit_at = now;
    changed = true;
    out += bashPrintf(`  %s${t(locale, "share.submit_ok")}%s

`, SHARE_GOLD, SHARE_RESET);
  } else if (code === 429) {
    out += bashPrintf(`  %s${t(locale, "share.cooldown", Math.floor(cooldownS / 3600))}%s

`, SHARE_DIM, SHARE_RESET);
  } else {
    out += bashPrintf(`  %s${t(locale, "share.submit_failed", code)}%s

`, SHARE_DIM, SHARE_RESET);
  }
  return { state: s, output: out, changed };
}
function runShare(input) {
  const { args, locale, anonId } = input;
  const data = JSON.parse(JSON.stringify(input.data));
  const L = (k, ...a) => t(locale, k, ...a);
  const sub = args[0] ?? "";
  const share = data.stats_share ?? {};
  const enabled = share.enabled === true;
  const endpoint = share.endpoint ?? "";
  const anonCur = share.anon_id ?? "";
  const displayName = share.display_name ?? "";
  let changed = false;
  const ensure = () => data.stats_share ??= {};
  let out = bashPrintf(`
  %s%s${L("share.title")}%s

`, BOLD4, GOLD4, RESET4);
  switch (sub) {
    case "enable":
    case "on": {
      if (enabled) {
        out += bashPrintf(`  %s${L("share.already_enabled")}%s

`, DIM4, RESET4);
        out += bashPrintf("  %s%s%s\n\n", DIM4, `anon_id : ${anonCur}`, RESET4);
        break;
      }
      if (args[1] !== "--confirm") {
        out += bashPrintf(`  %s${L("share.privacy_notice")}%s

`, DIM4, RESET4);
        out += bashPrintf(`  %s${L("share.confirm_hint")}%s

`, BOLD4, RESET4);
        break;
      }
      ensure().enabled = true;
      data.stats_share.anon_id = anonId;
      changed = true;
      out += bashPrintf(`  %s${L("share.enabled", anonId)}%s

`, GOLD4, RESET4);
      break;
    }
    case "disable":
    case "off": {
      if (!enabled) {
        out += bashPrintf(`  %s${L("share.already_disabled")}%s

`, DIM4, RESET4);
        break;
      }
      ensure().enabled = false;
      changed = true;
      out += bashPrintf(`  %s${L("share.disabled")}%s

`, DIM4, RESET4);
      out += bashPrintf(`  %s${L("share.disable_hint")}%s

`, DIM4, RESET4);
      break;
    }
    case "name":
    case "pseudo": {
      const newName = args[1] ?? "";
      if (newName === "") {
        out += displayName ? bashPrintf(`  %s${L("share.name_current", displayName)}%s

`, GOLD4, RESET4) : bashPrintf(`  %s${L("share.name_unset")}%s

`, DIM4, RESET4);
        out += bashPrintf(`  %s${L("share.name_usage")}%s

`, DIM4, RESET4);
        break;
      }
      if (newName === "clear" || newName === "remove") {
        ensure().display_name = null;
        changed = true;
        out += bashPrintf(`  %s${L("share.name_cleared")}%s

`, DIM4, RESET4);
        break;
      }
      if (!NAME_RE.test(newName)) {
        out += bashPrintf(`  %s${L("share.name_invalid")}%s

`, DIM4, RESET4);
        break;
      }
      ensure().display_name = newName;
      changed = true;
      out += bashPrintf(`  %s${L("share.name_set", newName)}%s

`, GOLD4, RESET4);
      out += bashPrintf(`  %s${L("share.name_set_hint")}%s

`, DIM4, RESET4);
      break;
    }
    case "status":
    case "": {
      if (enabled) {
        out += bashPrintf(`  %s${L("share.status_enabled", anonCur)}%s
`, GOLD4, RESET4);
        out += displayName ? bashPrintf(`  %s${L("share.status_pseudo", displayName)}%s
`, GOLD4, RESET4) : bashPrintf(`  %s${L("share.status_no_pseudo")}%s
`, DIM4, RESET4);
        out += bashPrintf(`  %s${L("share.status_endpoint", endpoint)}%s

`, DIM4, RESET4);
      } else {
        out += bashPrintf(`  %s${L("share.status_disabled")}%s

`, DIM4, RESET4);
      }
      out += bashPrintf(`  %s${L("share.usage")}%s

`, DIM4, RESET4);
      break;
    }
    default:
      return null;
  }
  return { data, output: out, changed };
}

// dist/arena.js
var RESET5 = "\x1B[0m";
var BOLD5 = "\x1B[1m";
var DIM5 = "\x1B[2m";
var GOLD5 = "\x1B[33m";
function buildTeam(state, anonId, displayName) {
  const lineage = state.lineage ?? "";
  const level = Number(state.current_level ?? 0);
  if (!lineage || level < 1)
    return null;
  const team = { anon_id: anonId, lineage, level, is_shiny: state.is_shiny ?? false };
  if (displayName !== "")
    team.display_name = displayName;
  return team;
}
function renderBattle(locale, raw) {
  const b = raw.battle ?? raw;
  const c = b.challenger ?? {};
  const d = b.defender ?? {};
  const cName = c.display_name ?? c.anon_id;
  const dName = d.display_name ?? d.anon_id;
  const cEmoji = lineageEmoji(c.lineage);
  const dEmoji = lineageEmoji(d.lineage);
  const cStar = c.is_shiny === true ? "\u2605" : "";
  const dStar = d.is_shiny === true ? "\u2605" : "";
  let out = bashPrintf("  %s%s %s %s%s %sLv.%s%s   %svs%s   %s%s %s %s%s %sLv.%s%s\n\n", BOLD5, cEmoji, cName, cStar, RESET5, DIM5, c.level, RESET5, DIM5, RESET5, BOLD5, dEmoji, dName, dStar, RESET5, DIM5, d.level, RESET5);
  for (const turn of b.turns ?? []) {
    const who = turn.actor === "challenger" ? cEmoji : dEmoji;
    const eff = String(turn.effectiveness);
    const effLabel = eff === "2.0" || eff === "2" ? "2.0\xD7" : eff === "0.5" ? "0.5\xD7" : "";
    const critLabel = turn.critical === true ? " CRIT!" : "";
    out += bashPrintf("  %sTurn %2s%s  %s -%s HP %s%s%s\n", DIM5, String(turn.turn), RESET5, who, turn.damage, DIM5, effLabel + critLabel, RESET5);
  }
  out += "\n";
  const winner = b.winner;
  if (winner === "challenger")
    out += bashPrintf(`  %s%s${t(locale, "arena.winner_challenger", cName)}%s

`, BOLD5, GOLD5, RESET5);
  else if (winner === "defender")
    out += bashPrintf(`  %s%s${t(locale, "arena.winner_defender", dName)}%s

`, BOLD5, GOLD5, RESET5);
  else
    out += bashPrintf(`  %s${t(locale, "arena.winner_draw")}%s

`, DIM5, RESET5);
  out += bashPrintf(`  %s${t(locale, "arena.battle_summary", (b.turns ?? []).length, b.reason)}%s

`, DIM5, RESET5);
  return out;
}
async function getJson(url, init) {
  try {
    const r = await fetch(url, init);
    if (!r.ok)
      return null;
    return await r.json();
  } catch {
    return null;
  }
}
async function postJson(url, init) {
  try {
    return await (await fetch(url, init)).json();
  } catch {
    return {};
  }
}
async function runArena(input) {
  const { locale, now } = input;
  const data = JSON.parse(JSON.stringify(input.data));
  const L = (k, ...a) => t(locale, k, ...a);
  const sub = input.args[0] ?? "status";
  const endpoint = data.stats_share?.endpoint ?? "";
  const webUrl = data.arena?.web_url ?? "https://claude-pokemon-arena.pages.dev";
  const anonId = data.stats_share?.anon_id ?? "";
  const displayName = data.stats_share?.display_name ?? "";
  const enabled = data.arena?.enabled === true;
  const secret = input.arenaSecret;
  let secretOp = null;
  let dataChanged = false;
  let out = bashPrintf(`
  %s%s${L("arena.title")}%s

`, BOLD5, GOLD5, RESET5);
  const line = (k, color, ...a) => {
    out += bashPrintf(`  %s${L(k, ...a)}%s

`, color, RESET5);
  };
  const ensureArena = () => data.arena ??= {};
  switch (sub) {
    case "enable":
    case "on": {
      if (!anonId) {
        line("arena.no_anon_id", DIM5);
        break;
      }
      if (enabled) {
        line("arena.already_enabled", DIM5);
        break;
      }
      if (input.args[1] !== "--confirm") {
        line("arena.privacy_notice", DIM5);
        line("arena.confirm_hint", BOLD5);
        break;
      }
      const team = buildTeam(input.state, anonId, displayName);
      if (!team) {
        line("arena.no_active", DIM5);
        break;
      }
      const resp = await postJson(`${endpoint}/v1/arena/enable`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(team)
      });
      const sec = resp.arena_secret ?? "";
      if (!sec) {
        const errCode = resp.error ?? "";
        let errMsg;
        if (errCode === "validation")
          errMsg = (resp.details ?? []).join("; ");
        else if (errCode === "already_enabled")
          errMsg = L("arena.already_enabled");
        else if (errCode === "")
          errMsg = typeof resp === "string" ? resp : JSON.stringify(resp);
        else
          errMsg = errCode;
        out += bashPrintf("  %s%s%s\n\n", DIM5, L("arena.enable_failed", errMsg), RESET5);
        break;
      }
      secretOp = { action: "save", value: sec };
      ensureArena().enabled = true;
      data.arena.enabled_at = now;
      dataChanged = true;
      line("arena.enabled", GOLD5, anonId);
      break;
    }
    case "disable":
    case "off": {
      if (!enabled) {
        line("arena.already_disabled", DIM5);
        break;
      }
      if (!secret) {
        line("arena.no_secret", DIM5);
        break;
      }
      await fetch(`${endpoint}/v1/arena/disable?anon_id=${anonId}`, {
        method: "DELETE",
        headers: { authorization: `Bearer ${secret}` }
      }).catch(() => void 0);
      secretOp = { action: "clear" };
      ensureArena().enabled = false;
      dataChanged = true;
      line("arena.disabled", DIM5);
      break;
    }
    case "regenerate":
    case "rotate": {
      if (!enabled) {
        line("arena.not_enabled", DIM5);
        break;
      }
      if (!secret) {
        line("arena.no_secret", DIM5);
        break;
      }
      const team = buildTeam(input.state, anonId, displayName);
      if (!team) {
        line("arena.no_active", DIM5);
        break;
      }
      const resp = await postJson(`${endpoint}/v1/arena/regenerate`, {
        method: "POST",
        headers: { "content-type": "application/json", authorization: `Bearer ${secret}` },
        body: JSON.stringify(team)
      });
      const newSec = resp.arena_secret ?? "";
      if (!newSec) {
        line("arena.regen_failed", DIM5, JSON.stringify(resp));
        break;
      }
      secretOp = { action: "save", value: newSec };
      line("arena.regen_ok", GOLD5);
      break;
    }
    case "opponents":
    case "list": {
      const limit = input.args[1] ?? "10";
      const resp = await getJson(`${endpoint}/v1/arena/opponents?limit=${limit}`);
      if (resp === null) {
        line("arena.fetch_failed", DIM5);
        break;
      }
      line("arena.opponents_count", DIM5, resp.total ?? 0);
      for (const o of resp.opponents ?? []) {
        const shinyMark = o.is_shiny === true ? " \u2605" : "";
        out += bashPrintf("  %s#%s%s  %s  Lv.%s  %s%s\n", DIM5, o.anon_id, RESET5, lineageEmoji(o.lineage), o.level, o.display_name ?? o.anon_id, shinyMark);
      }
      out += bashPrintf(`
  %s${L("arena.opponents_hint")}%s

`, DIM5, RESET5);
      break;
    }
    case "challenge":
    case "fight": {
      const target = input.args[1] ?? "";
      if (!target) {
        line("arena.challenge_usage", DIM5);
        break;
      }
      if (!enabled) {
        line("arena.not_enabled", DIM5);
        break;
      }
      if (!secret) {
        line("arena.no_secret", DIM5);
        break;
      }
      const resp = await postJson(`${endpoint}/v1/arena/challenge`, {
        method: "POST",
        headers: { "content-type": "application/json", authorization: `Bearer ${secret}` },
        body: JSON.stringify({ challenger_anon_id: anonId, defender_anon_id: target })
      });
      const battleId = resp.battle?.battle_id ?? "";
      if (!battleId) {
        line("arena.challenge_failed", DIM5, JSON.stringify(resp));
        break;
      }
      ensureArena().last_battle_id = battleId;
      dataChanged = true;
      out += renderBattle(locale, resp);
      line("arena.replay", DIM5, webUrl, battleId);
      break;
    }
    case "battle":
    case "view": {
      const id = input.args[1] || (data.arena?.last_battle_id ?? "");
      if (!id) {
        line("arena.battle_usage", DIM5);
        break;
      }
      const resp = await getJson(`${endpoint}/v1/arena/battle/${id}`);
      if (resp === null) {
        line("arena.battle_not_found", DIM5, id);
        break;
      }
      out += renderBattle(locale, resp);
      line("arena.replay", DIM5, webUrl, id);
      break;
    }
    case "status":
    case "": {
      if (enabled)
        out += bashPrintf(`  %s${L("arena.status_enabled", anonId)}%s
`, GOLD5, RESET5);
      else
        out += bashPrintf(`  %s${L("arena.status_disabled")}%s
`, DIM5, RESET5);
      out += bashPrintf(`  %s${L("arena.status_endpoint", endpoint)}%s

`, DIM5, RESET5);
      out += bashPrintf(`  %s${L("arena.usage")}%s

`, DIM5, RESET5);
      break;
    }
    default:
      return null;
  }
  return { data, output: out, dataChanged, secret: secretOp };
}

// dist/cli.js
import { randomBytes } from "node:crypto";

// dist/types.js
var COMBAT_TYPES = [
  "normal",
  "fire",
  "water",
  "electric",
  "grass",
  "ice",
  "fighting",
  "poison",
  "ground",
  "flying",
  "psychic",
  "bug",
  "rock",
  "ghost",
  "dragon",
  "dark",
  "steel",
  "fairy"
];

// dist/battle.js
var TYPE_CHART_OVERRIDES = {
  normal: { rock: 0.5, ghost: 0, steel: 0.5 },
  fire: { fire: 0.5, water: 0.5, grass: 2, ice: 2, bug: 2, rock: 0.5, dragon: 0.5, steel: 2 },
  water: { fire: 2, water: 0.5, grass: 0.5, ground: 2, rock: 2, dragon: 0.5 },
  electric: { water: 2, electric: 0.5, grass: 0.5, ground: 0, flying: 2, dragon: 0.5 },
  grass: {
    fire: 0.5,
    water: 2,
    grass: 0.5,
    poison: 0.5,
    ground: 2,
    flying: 0.5,
    bug: 0.5,
    rock: 2,
    dragon: 0.5,
    steel: 0.5
  },
  ice: { fire: 0.5, water: 0.5, grass: 2, ice: 0.5, ground: 2, flying: 2, dragon: 2, steel: 0.5 },
  fighting: {
    normal: 2,
    ice: 2,
    poison: 0.5,
    flying: 0.5,
    psychic: 0.5,
    bug: 0.5,
    rock: 2,
    ghost: 0,
    dark: 2,
    steel: 2,
    fairy: 0.5
  },
  poison: { grass: 2, poison: 0.5, ground: 0.5, rock: 0.5, ghost: 0.5, steel: 0, fairy: 2 },
  ground: { fire: 2, electric: 2, grass: 0.5, poison: 2, flying: 0, bug: 0.5, rock: 2, steel: 2 },
  flying: { electric: 0.5, grass: 2, fighting: 2, bug: 2, rock: 0.5, steel: 0.5 },
  psychic: { fighting: 2, poison: 2, psychic: 0.5, dark: 0, steel: 0.5 },
  bug: {
    fire: 0.5,
    grass: 2,
    fighting: 0.5,
    poison: 0.5,
    flying: 0.5,
    psychic: 2,
    ghost: 0.5,
    dark: 2,
    steel: 0.5,
    fairy: 0.5
  },
  rock: { fire: 2, ice: 2, fighting: 0.5, ground: 0.5, flying: 2, bug: 2, steel: 0.5 },
  ghost: { normal: 0, psychic: 2, ghost: 2, dark: 0.5 },
  dragon: { dragon: 2, steel: 0.5, fairy: 0 },
  dark: { fighting: 0.5, psychic: 2, ghost: 2, dark: 0.5, fairy: 0.5 },
  steel: { fire: 0.5, water: 0.5, electric: 0.5, ice: 2, rock: 2, steel: 0.5, fairy: 2 },
  fairy: { fire: 0.5, fighting: 2, poison: 0.5, dragon: 2, dark: 2, steel: 0.5 }
};
function buildTypeChart() {
  const chart = {};
  for (const attacker of COMBAT_TYPES) {
    chart[attacker] = {};
    for (const defender of COMBAT_TYPES) {
      chart[attacker][defender] = TYPE_CHART_OVERRIDES[attacker]?.[defender] ?? 1;
    }
  }
  return chart;
}
var TYPE_CHART = buildTypeChart();

// dist/cli.js
function derive(input) {
  const { thresholds, lineage } = input;
  const totalXp = Number(input.total_xp);
  const usedPct = input.used_pct == null ? null : Number(input.used_pct);
  const level = input.level == null ? levelFromXp(thresholds, totalXp) : Number(input.level);
  const typeMatch = typeMatchMultiplier(lineage, usedPct == null ? 50 : usedPct);
  return {
    level,
    threshold: thresholdFor(thresholds, level),
    xp_to_next: xpToNext(thresholds, totalXp, level),
    progress_pct: progressPct(thresholds, totalXp, level),
    xp_multiplier: xpMultiplier(usedPct).toFixed(1),
    type_match_mult: typeMatch.toFixed(1)
  };
}
var COMMANDS = {
  derive: (input) => derive(input)
};
async function readStdin() {
  const chunks = [];
  for await (const chunk of process.stdin)
    chunks.push(chunk);
  return Buffer.concat(chunks).toString("utf8");
}
function mutate(input) {
  const { op, state, now, data } = input;
  const args = Array.isArray(input.args) ? input.args : [];
  switch (op) {
    case "team_to_pc":
      return { ok: true, state: teamToPc(state, Number(args[0])) };
    case "release_slot":
      return { ok: true, state: releaseSlot(state, args[0], Number(args[1])) };
    case "pc_to_team_or_active": {
      const next = pcToTeamOrActive(state, now, Number(args[0]));
      return { ok: next !== null, state: next };
    }
    case "switch_companion":
      return { ok: true, state: switchCompanion(state, now, Number(args[0])) };
    case "hatch":
      return { ok: true, state: hatch(state, now, data, args[0] || void 0) };
    case "ceremonial_reset":
      return { ok: true, state: ceremonialReset(state, now, data) };
    default:
      return null;
  }
}
async function net(view, args, input) {
  const data = input.data;
  const locale = input.locale;
  const endpoint = data?.stats_share?.endpoint ?? "";
  const get = async (path) => {
    if (!endpoint)
      return { endpoint: false };
    try {
      const r = await fetch(`${endpoint}${path}`);
      if (!r.ok)
        return { fetchFailed: true };
      return { resp: await r.json() };
    } catch {
      return { fetchFailed: true };
    }
  };
  switch (view) {
    case "leaderboard": {
      const metric = args[0] || "total_tokens";
      const limit = args[1] || "10";
      return renderLeaderboard(data, locale, metric, await get(`/v1/leaderboard?metric=${metric}&limit=${limit}`));
    }
    case "aggregate":
      return renderAggregate(data, locale, await get("/v1/aggregate"));
    default:
      return null;
  }
}
async function main() {
  const command = process.argv[2];
  const isRender = command === "render";
  const isMutate = command === "mutate";
  const isTick = command === "tick";
  const isNet = command === "net";
  const isConfig = command === "config";
  const isShare = command === "share";
  const isArena = command === "arena";
  const handler = command ? COMMANDS[command] : void 0;
  if (!handler && !isRender && !isMutate && !isTick && !isNet && !isConfig && !isShare && !isArena) {
    process.stderr.write(`engine: unknown command ${JSON.stringify(command)} (expected: ${[...Object.keys(COMMANDS), "render", "mutate", "tick", "net", "config", "share", "arena"].join(", ")})
`);
    process.exit(2);
  }
  const raw = await readStdin();
  let input;
  try {
    input = JSON.parse(raw);
  } catch {
    process.stderr.write("engine: invalid JSON on stdin\n");
    process.exit(2);
    return;
  }
  if (isRender) {
    const inp = input;
    const argView = process.argv[3];
    if (argView)
      inp.view = argView;
    const { supported, output } = renderView(inp);
    if (!supported)
      process.exit(3);
    process.stdout.write(output);
    return;
  }
  if (isMutate) {
    const argOp = process.argv[3];
    const inp = input;
    if (argOp)
      inp.op = argOp;
    const result = mutate(inp);
    if (result === null)
      process.exit(3);
    process.stdout.write(JSON.stringify(result));
    return;
  }
  if (isTick) {
    process.stdout.write(JSON.stringify(tick(input)));
    return;
  }
  if (isNet) {
    const view = process.argv[3];
    const out = await net(view, process.argv.slice(4), input);
    if (out === null)
      process.exit(3);
    process.stdout.write(out);
    return;
  }
  if (isConfig) {
    const cmd = process.argv[3];
    if (cmd !== "quote" && cmd !== "bio" && cmd !== "pins")
      process.exit(3);
    const inp = input;
    const result = runConfig({
      cmd,
      args: process.argv.slice(4),
      data: inp.data,
      state: inp.state,
      locale: inp.locale
    });
    process.stdout.write(JSON.stringify(result));
    return;
  }
  if (isShare) {
    const inp = input;
    const data = inp.data;
    const state = inp.state;
    const locale = inp.locale;
    const sub = process.argv[3] ?? "";
    const endpoint = data?.stats_share?.endpoint ?? "";
    const nowIso = (/* @__PURE__ */ new Date()).toISOString().replace(/\.\d{3}Z$/, "Z");
    if (sub === "forget") {
      const anonId = data?.stats_share?.anon_id ?? "";
      let ok = false;
      if (anonId && endpoint) {
        try {
          const r = await fetch(`${endpoint}/v1/forget?anon_id=${anonId}`, { method: "DELETE" });
          ok = r.ok && (await r.text()).length > 0;
        } catch {
          ok = false;
        }
      }
      const res = renderForget(data, locale, anonId, ok);
      process.stdout.write(JSON.stringify({ data: res.data, state, output: res.output, dataChanged: res.changed, stateChanged: false }));
      return;
    }
    if (sub === "submit" || sub === "push") {
      const enabled = data?.stats_share?.enabled === true;
      let code = 0;
      let cooldownS = 0;
      if (enabled && endpoint) {
        const payload = buildSubmitPayload(data, state, data.stats_share.anon_id ?? "", data.version ?? "unknown", data.stats_share.display_name ?? "", nowIso);
        try {
          const r = await fetch(`${endpoint}/v1/submit`, {
            method: "POST",
            headers: { "content-type": "application/json" },
            body: JSON.stringify(payload)
          });
          code = r.status;
          if (code === 429) {
            try {
              cooldownS = (await r.json()).cooldown_remaining_s ?? 0;
            } catch {
              cooldownS = 0;
            }
          }
        } catch {
          code = 0;
        }
      }
      const res = renderSubmit(state, locale, enabled, code, cooldownS, nowIso);
      process.stdout.write(JSON.stringify({ data, state: res.state, output: res.output, dataChanged: false, stateChanged: res.changed }));
      return;
    }
    const result = runShare({ args: process.argv.slice(3), data, locale, anonId: randomBytes(4).toString("hex") });
    if (result === null)
      process.exit(3);
    process.stdout.write(JSON.stringify({ data: result.data, state, output: result.output, dataChanged: result.changed, stateChanged: false }));
    return;
  }
  if (isArena) {
    const inp = input;
    const result = await runArena({
      args: process.argv.slice(3),
      data: inp.data,
      state: inp.state,
      locale: inp.locale,
      arenaSecret: inp.arenaSecret ?? "",
      now: inp.now ?? (/* @__PURE__ */ new Date()).toISOString().replace(/\.\d{3}Z$/, "Z")
    });
    if (result === null)
      process.exit(3);
    process.stdout.write(JSON.stringify(result));
    return;
  }
  process.stdout.write(JSON.stringify(handler(input)));
}
function invokedAsScript() {
  const entry = process.argv[1];
  if (!entry)
    return false;
  try {
    return realpathSync(entry) === realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return false;
  }
}
if (invokedAsScript()) {
  main().catch((err) => {
    process.stderr.write(`engine: ${err instanceof Error ? err.message : String(err)}
`);
    process.exit(1);
  });
}
export {
  derive
};
