// GENERATED by shared/scripts/build-engine.mjs — do not edit. Run `npm run build:data`.

// dist/cli.js
import { fileURLToPath } from "node:url";
import { realpathSync } from "node:fs";

// dist/types.js
var COMBAT_TYPES = [
  "normal",
  "fire",
  "water",
  "electric",
  "grass",
  "ice",
  "fighting",
  "poison",
  "ground",
  "flying",
  "psychic",
  "bug",
  "rock",
  "ghost",
  "dragon",
  "dark",
  "steel",
  "fairy"
];

// dist/battle.js
var TYPE_CHART_OVERRIDES = {
  normal: { rock: 0.5, ghost: 0, steel: 0.5 },
  fire: { fire: 0.5, water: 0.5, grass: 2, ice: 2, bug: 2, rock: 0.5, dragon: 0.5, steel: 2 },
  water: { fire: 2, water: 0.5, grass: 0.5, ground: 2, rock: 2, dragon: 0.5 },
  electric: { water: 2, electric: 0.5, grass: 0.5, ground: 0, flying: 2, dragon: 0.5 },
  grass: {
    fire: 0.5,
    water: 2,
    grass: 0.5,
    poison: 0.5,
    ground: 2,
    flying: 0.5,
    bug: 0.5,
    rock: 2,
    dragon: 0.5,
    steel: 0.5
  },
  ice: { fire: 0.5, water: 0.5, grass: 2, ice: 0.5, ground: 2, flying: 2, dragon: 2, steel: 0.5 },
  fighting: {
    normal: 2,
    ice: 2,
    poison: 0.5,
    flying: 0.5,
    psychic: 0.5,
    bug: 0.5,
    rock: 2,
    ghost: 0,
    dark: 2,
    steel: 2,
    fairy: 0.5
  },
  poison: { grass: 2, poison: 0.5, ground: 0.5, rock: 0.5, ghost: 0.5, steel: 0, fairy: 2 },
  ground: { fire: 2, electric: 2, grass: 0.5, poison: 2, flying: 0, bug: 0.5, rock: 2, steel: 2 },
  flying: { electric: 0.5, grass: 2, fighting: 2, bug: 2, rock: 0.5, steel: 0.5 },
  psychic: { fighting: 2, poison: 2, psychic: 0.5, dark: 0, steel: 0.5 },
  bug: {
    fire: 0.5,
    grass: 2,
    fighting: 0.5,
    poison: 0.5,
    flying: 0.5,
    psychic: 2,
    ghost: 0.5,
    dark: 2,
    steel: 0.5,
    fairy: 0.5
  },
  rock: { fire: 2, ice: 2, fighting: 0.5, ground: 0.5, flying: 2, bug: 2, steel: 0.5 },
  ghost: { normal: 0, psychic: 2, ghost: 2, dark: 0.5 },
  dragon: { dragon: 2, steel: 0.5, fairy: 0 },
  dark: { fighting: 0.5, psychic: 2, ghost: 2, dark: 0.5, fairy: 0.5 },
  steel: { fire: 0.5, water: 0.5, electric: 0.5, ice: 2, rock: 2, steel: 0.5, fairy: 2 },
  fairy: { fire: 0.5, fighting: 2, poison: 0.5, dragon: 2, dark: 2, steel: 0.5 }
};
function buildTypeChart() {
  const chart = {};
  for (const attacker of COMBAT_TYPES) {
    chart[attacker] = {};
    for (const defender of COMBAT_TYPES) {
      chart[attacker][defender] = TYPE_CHART_OVERRIDES[attacker]?.[defender] ?? 1;
    }
  }
  return chart;
}
var TYPE_CHART = buildTypeChart();

// dist/xp.js
function thresholdFor(thresholds, level) {
  return thresholds[level];
}
function levelFromXp(thresholds, totalXp) {
  let count = 0;
  for (const t of thresholds)
    if (t <= totalXp)
      count++;
  return count - 1;
}
function xpToNext(thresholds, totalXp, level) {
  const maxLevel = thresholds.length - 1;
  if (level >= maxLevel)
    return 0;
  return thresholds[level + 1] - totalXp;
}
function progressPct(thresholds, totalXp, level) {
  const maxLevel = thresholds.length - 1;
  if (level >= maxLevel)
    return 100;
  const cur = thresholds[level];
  const nxt = thresholds[level + 1];
  const pct = Math.floor((totalXp - cur) * 100 / (nxt - cur));
  if (pct < 0)
    return 0;
  if (pct > 100)
    return 100;
  return pct;
}
function xpMultiplier(usedPct) {
  if (usedPct == null)
    return 1;
  const p = Math.round(usedPct);
  if (p <= 25)
    return 2;
  if (p <= 50)
    return 1.5;
  if (p <= 75)
    return 1;
  return 0.5;
}
function typeMatchMultiplier(lineage, usedPct) {
  const p = Math.round(usedPct);
  switch (lineage) {
    case "fire":
      return p < 30 ? 1.2 : 1;
    case "water":
      return p > 70 ? 1.2 : 1;
    case "grass":
      return p >= 40 && p <= 60 ? 1.2 : 1;
    case "electric":
      return 1.2;
    case "eevee":
      return 1.1;
    default:
      return 1;
  }
}

// dist/cli.js
function derive(input) {
  const { thresholds, lineage } = input;
  const totalXp = Number(input.total_xp);
  const usedPct = input.used_pct == null ? null : Number(input.used_pct);
  const level = input.level == null ? levelFromXp(thresholds, totalXp) : Number(input.level);
  const typeMatch = typeMatchMultiplier(lineage, usedPct == null ? 50 : usedPct);
  return {
    level,
    threshold: thresholdFor(thresholds, level),
    xp_to_next: xpToNext(thresholds, totalXp, level),
    progress_pct: progressPct(thresholds, totalXp, level),
    xp_multiplier: xpMultiplier(usedPct).toFixed(1),
    type_match_mult: typeMatch.toFixed(1)
  };
}
var COMMANDS = {
  derive: (input) => derive(input)
};
async function readStdin() {
  const chunks = [];
  for await (const chunk of process.stdin)
    chunks.push(chunk);
  return Buffer.concat(chunks).toString("utf8");
}
async function main() {
  const command = process.argv[2];
  const handler = command ? COMMANDS[command] : void 0;
  if (!handler) {
    process.stderr.write(`engine: unknown command ${JSON.stringify(command)} (expected: ${Object.keys(COMMANDS).join(", ")})
`);
    process.exit(2);
  }
  const raw = await readStdin();
  let input;
  try {
    input = JSON.parse(raw);
  } catch {
    process.stderr.write("engine: invalid JSON on stdin\n");
    process.exit(2);
    return;
  }
  process.stdout.write(JSON.stringify(handler(input)));
}
function invokedAsScript() {
  const entry = process.argv[1];
  if (!entry)
    return false;
  try {
    return realpathSync(entry) === realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return false;
  }
}
if (invokedAsScript()) {
  main().catch((err) => {
    process.stderr.write(`engine: ${err instanceof Error ? err.message : String(err)}
`);
    process.exit(1);
  });
}
export {
  derive
};
