// GENERATED by cli/scripts/build-engine.mjs — do not edit. Run `npm run build:data`.

// cli/dist/statusline-entry.js
import { readFileSync as readFileSync2, readdirSync } from "node:fs";
import { join as join2 } from "node:path";
import { execFileSync, spawn } from "node:child_process";

// shared/dist/xp.js
function levelFromXp(thresholds, totalXp) {
  let count = 0;
  for (const t2 of thresholds)
    if (t2 <= totalXp)
      count++;
  return count - 1;
}
function progressPct(thresholds, totalXp, level) {
  const maxLevel = thresholds.length - 1;
  if (level >= maxLevel)
    return 100;
  const cur = thresholds[level];
  const nxt = thresholds[level + 1];
  const pct = Math.floor((totalXp - cur) * 100 / (nxt - cur));
  if (pct < 0)
    return 0;
  if (pct > 100)
    return 100;
  return pct;
}
function xpMultiplier(usedPct) {
  if (usedPct == null)
    return 1;
  const p = Math.round(usedPct);
  if (p <= 25)
    return 2;
  if (p <= 50)
    return 1.5;
  if (p <= 75)
    return 1;
  return 0.5;
}
function typeMatchMultiplier(lineage, usedPct) {
  const p = Math.round(usedPct);
  switch (lineage) {
    case "fire":
      return p < 30 ? 1.2 : 1;
    case "water":
      return p > 70 ? 1.2 : 1;
    case "grass":
      return p >= 40 && p <= 60 ? 1.2 : 1;
    case "electric":
      return 1.2;
    case "eevee":
      return 1.1;
    default:
      return 1;
  }
}

// cli/dist/render/views/format.js
function jqStr(v) {
  return v === null || v === void 0 ? "null" : String(v);
}

// cli/dist/render/views/stage.js
function resolveStageDefault(data, lineage, level) {
  const stages = data.lineages?.[lineage]?.stages ?? [];
  const n = Number(level);
  if (level === null || level === void 0 || level === "" || !Number.isFinite(n))
    return null;
  const candidates = stages.filter((s) => s.min_level <= n);
  if (candidates.length === 0)
    return null;
  const maxLvl = Math.max(...candidates.map((s) => s.min_level));
  return stages.find((s) => s.min_level === maxLvl) ?? null;
}
function eeveeFormStage(data, form) {
  const stages = data.lineages?.eevee?.stages ?? [];
  return stages.find((s) => s.showdown_id === form) ?? null;
}
function evoField(data, state, lineage, level, field) {
  const n = Number(level);
  const valid = level !== null && level !== void 0 && level !== "" && Number.isFinite(n);
  if (lineage === "eevee" && valid && n >= 30) {
    const form = state.eevee_form;
    if (form) {
      const st2 = eeveeFormStage(data, form);
      return jqStr(st2 ? st2[field] : null);
    }
  }
  const st = resolveStageDefault(data, lineage, level);
  return jqStr(st ? st[field] : null);
}

// cli/dist/collection.js
function clone(v) {
  return JSON.parse(JSON.stringify(v));
}
function lastStageName(state) {
  const hist = Array.isArray(state.evolution_history) ? state.evolution_history : [];
  const name = hist.length ? hist[hist.length - 1]?.name : void 0;
  return name ?? "\u0152uf";
}
function activeToArchive(state, now) {
  if (state.lineage == null)
    return clone(state);
  const lin = state.lineage;
  const s = clone(state);
  const team = Array.isArray(s.team) ? s.team : [];
  s.team = team;
  team.push({
    lineage: s.lineage,
    is_shiny: s.is_shiny,
    level: s.current_level,
    total_xp: s.total_xp,
    max_stage: lastStageName(s),
    evolution_history: s.evolution_history,
    eevee_form: s.eevee_form,
    items: s.items,
    created_at: s.created_at,
    completed_at: now
  });
  if (team.length > 6) {
    const pc = Array.isArray(s.pc_storage) ? s.pc_storage : [];
    s.pc_storage = pc;
    pc.push(team[0]);
    s.team = team.slice(1);
  }
  const ls = s.lifetime_stats = s.lifetime_stats ?? {};
  if ((s.current_level ?? 0) >= 100) {
    ls.total_companions = (ls.total_companions ?? ls.total_compagnons ?? 0) + 1;
    delete ls.total_compagnons;
  }
  const completed = Array.isArray(ls.lineages_completed) ? ls.lineages_completed : [];
  if (completed.indexOf(lin) === -1 && (s.current_level ?? 0) >= 100) {
    ls.lineages_completed = [...completed, lin];
  }
  return s;
}
function resetActive(state, now, forcedLineage) {
  const s = clone(state);
  s.lineage = forcedLineage != null && forcedLineage !== "" ? forcedLineage : null;
  s.is_shiny = false;
  s.current_level = 0;
  s.total_xp = 0;
  s.evolution_history = [];
  s.evolution_flash_remaining = 10;
  s.created_at = now;
  s.eevee_form = null;
  s.items = {};
  return s;
}
function archiveToTeam(state, now) {
  return resetActive(activeToArchive(state, now), now);
}
function checkBadges(state, now, data) {
  const s = clone(state);
  const badges = Array.isArray(s.badges) ? s.badges : [];
  s.badges = badges;
  const add = (id) => {
    if (!badges.some((b) => b && b.id === id))
      badges.push({ id, earned_at: now });
  };
  const ls = s.lifetime_stats ?? {};
  const hist = Array.isArray(s.evolution_history) ? s.evolution_history : [];
  const wildSeen = Object.keys(s.pokedex_wild ?? {});
  const wildCount = wildSeen.length;
  const pool = Array.isArray(data?.wild_pool) ? data.wild_pool : [];
  const kanto = pool.filter((w) => (w.national_dex ?? 0) >= 1 && (w.national_dex ?? 0) <= 151).map((w) => w.id);
  const johto = pool.filter((w) => (w.national_dex ?? 0) >= 152 && (w.national_dex ?? 0) <= 251).map((w) => w.id);
  const hasAllOf = (ids) => ids.length > 0 && ids.every((id) => wildSeen.includes(id));
  const completed = Array.isArray(ls.lineages_completed) ? ls.lineages_completed : [];
  const pokedexSeen = Object.values(s.pokedex ?? {}).filter((v) => v && v.seen).length;
  if (hist.some((e) => e.level === 1))
    add("hatch");
  if (hist.some((e) => (e.level ?? 0) >= 16))
    add("first_evolution");
  if ((ls.total_shinies ?? 0) > 0)
    add("first_shiny");
  if ((ls.max_level ?? 0) >= 100)
    add("champion");
  if ((ls.total_tokens ?? 0) >= 1e8)
    add("centurion");
  if ((ls.total_shinies ?? 0) >= 5)
    add("constellation");
  if (pokedexSeen >= 5)
    add("master_pokedex");
  if (wildCount >= 50)
    add("dex_50");
  if (wildCount >= 100)
    add("dex_100");
  if (hasAllOf(kanto))
    add("regional_kanto");
  if (hasAllOf(johto))
    add("regional_johto");
  for (const lin of [
    "fire",
    "water",
    "grass",
    "electric",
    "eevee",
    "chikorita",
    "cyndaquil",
    "totodile"
  ]) {
    if (completed.includes(lin))
      add(`master_${lin}`);
  }
  return s;
}

// cli/dist/tick.js
function clone2(v) {
  return JSON.parse(JSON.stringify(v));
}
function prepend10(list, ev) {
  return [ev, ...Array.isArray(list) ? list : []].slice(0, 10);
}
function migrateSchema(c) {
  const s = c.s;
  s.badges ??= [];
  s.team ??= [];
  s.pc_storage ??= [];
  c.pokedex = s.pokedex ??= {};
  c.ls = s.lifetime_stats ??= {
    total_tokens: 0,
    total_evolutions: 0,
    total_shinies: 0,
    max_level: 0,
    lineages_completed: [],
    total_companions: 1,
    first_shiny_at: null
  };
  const ls = c.ls;
  if (ls.total_companions === void 0 && ls.total_compagnons !== void 0) {
    ls.total_companions = ls.total_compagnons;
  }
  delete ls.total_compagnons;
}
function backfillRetroactive(c) {
  const { s, pokedex, ls } = c;
  ls.max_level = (ls.max_level ?? 0) > (s.current_level ?? 0) ? ls.max_level : s.current_level;
  const linNow = s.lineage ?? "";
  if (linNow !== "" && (pokedex[linNow] ?? null) == null) {
    pokedex[linNow] = {
      seen: true,
      count: 1,
      first_seen_at: s.created_at,
      shiny_seen: s.is_shiny,
      shiny_count: s.is_shiny ? 1 : 0
    };
  }
  if (linNow !== "" && s.is_shiny === true && (pokedex[linNow]?.shiny_seen ?? false) === false) {
    const pd = pokedex[linNow];
    if (pd) {
      pd.shiny_seen = true;
      pd.shiny_count = (pd.shiny_count ?? 0) + 1;
    }
  }
  if (s.is_shiny === true && ls.total_shinies === 0) {
    ls.total_shinies = 1;
    ls.first_shiny_at ??= s.created_at;
  }
}
function assignLineage(c) {
  const { s, pokedex, decisions, now } = c;
  let lineage = s.lineage ?? "";
  if (!lineage) {
    lineage = decisions.starter;
    s.lineage = lineage;
    const pd = pokedex[lineage] ??= {
      seen: false,
      shiny_seen: false,
      count: 0,
      shiny_count: 0,
      first_seen_at: null
    };
    pd.seen = true;
    pd.count = (pd.count ?? 0) + 1;
    pd.first_seen_at ??= now;
  }
  c.lineage = lineage;
}
function clampLevelToXp(c) {
  const { s, thresholds } = c;
  const expectedLevel = levelFromXp(thresholds, s.total_xp ?? 0);
  if ((s.current_level ?? 0) > expectedLevel) {
    s.current_level = expectedLevel;
    s.evolution_flash_remaining = 0;
  }
  c.isShiny = s.is_shiny ?? false;
  c.prevLevel = s.current_level ?? 0;
}
function accumulateTokenDelta(c) {
  const { s, sid, currentTokens, nowEpoch } = c;
  const sessions = s.sessions ??= {};
  const sess = sessions[sid] ??= {};
  const prevTokens = sess.last_tick_tokens ?? sess.max_context_tokens ?? 0;
  const rawDelta = currentTokens > prevTokens ? currentTokens - prevTokens : 0;
  let pending = (sess.pending_tokens ?? 0) + rawDelta;
  const lastCreditAt = sess.last_xp_credit_at ?? 0;
  const gapS = nowEpoch - lastCreditAt;
  let delta = 0;
  const TICK_CAP = 1e4;
  if (gapS >= 30 && pending > 0) {
    delta = pending > TICK_CAP ? TICK_CAP : pending;
    pending -= delta;
    sess.last_xp_credit_at = nowEpoch;
  }
  sess.pending_tokens = pending;
  c.sess = sess;
  c.rawDelta = rawDelta;
  c.delta = delta;
}
function computeMultipliers(c) {
  const { s, data, now, usedPct, lineage, delta } = c;
  const xpMult = xpMultiplier(usedPct);
  const typeMatch = typeMatchMultiplier(lineage, usedPct == null ? 50 : usedPct);
  const today = now.slice(0, 10);
  let dailyMult = 1;
  if ((s.last_daily_bonus_date ?? "") !== today) {
    dailyMult = 1.5;
    s.last_daily_bonus_date = today;
  }
  const pctInt = Math.round(usedPct ?? 0);
  if (pctInt >= 90)
    s.high_context_streak = (s.high_context_streak ?? 0) + 1;
  else
    s.high_context_streak = 0;
  let statusMult = 1;
  if ((s.high_context_streak ?? 0) >= 5) {
    s.status = "tired";
    statusMult = 0.75;
  } else {
    s.status = "ok";
    statusMult = 1;
  }
  const heldItem = s.held_item ?? "";
  let heldMult = 1;
  if (heldItem)
    heldMult = Number(data.items?.[heldItem]?.effect_xp_mult ?? 1);
  const injuredTicks = s.injured_ticks_remaining ?? 0;
  let injuredMult = 1;
  if (injuredTicks > 0) {
    injuredMult = 0.75;
    s.injured_ticks_remaining = injuredTicks - 1;
    if (heldItem === "oran_berry") {
      s.held_item = null;
      s.injured_ticks_remaining = 0;
      injuredMult = 1;
    }
  }
  const shinyHunter = data.shiny_hunter_mode === true;
  const d = new Date(now);
  const curMonth = d.getUTCMonth() + 1;
  const curDay = d.getUTCDate();
  let seasonMult = 1;
  for (const season of Object.values(data.seasons ?? {})) {
    if (curMonth === season.month && curDay >= (season.day_start ?? Infinity) && curDay <= (season.day_end ?? -Infinity)) {
      seasonMult = Number(season.boost_mult_xp ?? 1);
      break;
    }
  }
  let weightedDelta = 0;
  if (!shinyHunter) {
    let m = xpMult * typeMatch * dailyMult * statusMult * heldMult * injuredMult * seasonMult;
    if (m > 2)
      m = 2;
    weightedDelta = Math.trunc(delta * m);
  }
  s.last_xp_multipliers = {
    context: xpMult.toFixed(1),
    type_match: typeMatch.toFixed(1),
    daily_bonus: dailyMult.toFixed(1),
    status: statusMult === 0.75 ? "0.75" : "1.0"
  };
  c.d = d;
  c.xpMult = xpMult;
  c.typeMatch = typeMatch;
  c.dailyMult = dailyMult;
  c.statusMult = statusMult;
  c.heldMult = heldMult;
  c.injuredMult = injuredMult;
  c.seasonMult = seasonMult;
  c.shinyHunter = shinyHunter;
  c.weightedDelta = weightedDelta;
}
function applyRandomEvents(c) {
  const { s, data, now, decisions } = c;
  if (decisions.berry.fired) {
    const b = (data.berries ?? [])[decisions.berry.index];
    if (b) {
      s.total_xp = (s.total_xp ?? 0) + (b.xp_bonus ?? 0);
      s.recent_events = prepend10(s.recent_events, {
        type: "berry",
        id: b.id,
        name: b.name,
        emoji: b.emoji,
        xp: b.xp_bonus,
        at: now
      });
    }
  }
  if (decisions.encounter.fired) {
    const w = (data.wild_pool ?? [])[decisions.encounter.index];
    if (!w)
      return;
    const wild = s.pokedex_wild ??= {};
    wild[w.id] = {
      count: (wild[w.id]?.count ?? 0) + 1,
      first_seen_at: wild[w.id]?.first_seen_at ?? now,
      last_seen_at: now
    };
    s.recent_events = prepend10(s.recent_events, { type: "encounter", id: w.id, at: now });
    if (decisions.battle.fired) {
      const ownLevel = s.current_level ?? 0;
      const wildLevel = decisions.battle.wild_level;
      const battleWon = ownLevel >= wildLevel - 3;
      if (battleWon) {
        const bonusXp = Math.trunc(decisions.battle.bonus_xp_raw * wildLevel / 25);
        s.total_xp = (s.total_xp ?? 0) + bonusXp;
        s.recent_events = prepend10(s.recent_events, {
          type: "battle_won",
          id: w.id,
          wild_level: wildLevel,
          xp: bonusXp,
          at: now
        });
      } else {
        s.injured_ticks_remaining = data.battle_injured_ticks ?? 5;
        s.recent_events = prepend10(s.recent_events, {
          type: "battle_lost",
          id: w.id,
          wild_level: wildLevel,
          at: now
        });
      }
    }
    if (decisions.item.fired) {
      const itemKeys = Object.keys(data.items ?? {}).sort();
      const itemId = itemKeys[decisions.item.index];
      if (itemId) {
        const inv = s.items ??= {};
        inv[itemId] = (inv[itemId] ?? 0) + 1;
        s.recent_events = prepend10(s.recent_events, {
          type: "item",
          id: itemId,
          name: data.items?.[itemId]?.name,
          emoji: data.items?.[itemId]?.emoji,
          at: now
        });
      }
    }
  }
}
function creditXp(c) {
  const { s, ls, sess, now, currentTokens, weightedDelta, rawDelta } = c;
  s.total_xp = (s.total_xp ?? 0) + weightedDelta;
  ls.total_tokens = (ls.total_tokens ?? 0) + rawDelta;
  sess.first_seen ??= now;
  sess.last_seen = now;
  sess.max_context_tokens = (sess.max_context_tokens ?? 0) > currentTokens ? sess.max_context_tokens : currentTokens;
  sess.last_tick_tokens = currentTokens;
  s.last_updated = now;
  if (!sess.baseline) {
    sess.baseline = {
      total_xp: s.total_xp - weightedDelta,
      friendship: s.friendship ?? 0,
      lifetime_tokens: ls.total_tokens - rawDelta,
      lineage: s.lineage,
      current_level: s.current_level,
      evolution_count: (s.evolution_history ?? []).length,
      badge_count: (s.badges ?? []).length,
      pokedex_wild_count: Object.keys(s.pokedex_wild ?? {}).length,
      games_won: ls.games_won ?? 0
    };
  }
}
function resolveLevelUpAndEvolution(c) {
  const { s, data, now, decisions, pokedex, ls, lineage, prevLevel, maxLevel, d } = c;
  let isShiny = c.isShiny;
  const totalXp = s.total_xp;
  const newLevel = levelFromXp(c.thresholds, totalXp);
  if (newLevel > prevLevel) {
    if (prevLevel === 0 && newLevel >= 1) {
      isShiny = decisions.shiny;
      s.is_shiny = isShiny;
      if (isShiny) {
        const pd = pokedex[lineage] ??= {
          seen: false,
          shiny_seen: false,
          count: 0,
          shiny_count: 0,
          first_seen_at: null
        };
        pd.shiny_seen = true;
        pd.shiny_count = (pd.shiny_count ?? 0) + 1;
        ls.total_shinies = (ls.total_shinies ?? 0) + 1;
        ls.first_shiny_at ??= now;
      }
    }
    if (lineage === "eevee" && prevLevel < 30 && newLevel >= 30) {
      const rules = data.eevee_evolution_rules ?? {};
      let chosenForm = "";
      let usedStone = "";
      for (const stone of ["fire_stone", "water_stone", "thunder_stone"]) {
        if ((s.items?.[stone] ?? 0) > 0) {
          usedStone = stone;
          chosenForm = rules[stone] ?? "";
          break;
        }
      }
      if (!chosenForm) {
        const friendship = s.friendship ?? 0;
        const threshold = data.eevee_friendship_threshold ?? 50;
        const hour = d.getUTCHours();
        if (friendship >= threshold) {
          chosenForm = (hour >= 6 && hour < 18 ? rules.day_default : rules.night_default) ?? "";
        } else {
          const fallback = ["fire_stone", "water_stone", "thunder_stone"][decisions.eevee_fallback_index] ?? "";
          chosenForm = rules[fallback] ?? "";
        }
      }
      s.eevee_form = chosenForm;
      if (usedStone) {
        const inv = s.items;
        inv[usedStone] -= 1;
        if (inv[usedStone] <= 0)
          delete inv[usedStone];
      }
    }
    const stages = data.lineages?.[lineage]?.stages ?? [];
    const transitions = stages.filter((st) => st.min_level > prevLevel && st.min_level <= newLevel).map((st) => st.min_level);
    let stageChanged = false;
    let transitionCount = 0;
    let eeveeLogged = false;
    for (const t2 of transitions) {
      if (lineage === "eevee" && t2 === 30 && eeveeLogged)
        continue;
      const evoName = evoField(data, s, lineage, t2, "name");
      s.evolution_history = [
        ...s.evolution_history ?? [],
        { level: t2, name: evoName, evolved_at: now, is_shiny: isShiny }
      ];
      stageChanged = true;
      transitionCount += 1;
      if (lineage === "eevee" && t2 === 30)
        eeveeLogged = true;
    }
    if (transitionCount > 0)
      ls.total_evolutions = (ls.total_evolutions ?? 0) + transitionCount;
    ls.max_level = (ls.max_level ?? 0) > newLevel ? ls.max_level : newLevel;
    const flashValue = stageChanged ? 3 : 0;
    s.current_level = newLevel;
    if (flashValue > 0)
      s.evolution_flash_remaining = flashValue;
    if (prevLevel < maxLevel && newLevel >= maxLevel) {
      Object.assign(s, archiveToTeam(s, now));
    }
  } else {
    const flash = s.evolution_flash_remaining ?? 0;
    if (flash > 0)
      s.evolution_flash_remaining = flash - 1;
  }
  c.isShiny = isShiny;
}
function bumpPerTickCounters(c) {
  const { s, lineage } = c;
  s.animation_frame_index = (s.animation_frame_index ?? 0) + 1;
  if (lineage && lineage !== "null")
    s.friendship = (s.friendship ?? 0) + 1;
}
function awardBadges(c) {
  Object.assign(c.s, checkBadges(c.s, c.now, c.data));
}
function pruneOldSessions(c) {
  const { s, sid, nowEpoch } = c;
  const cutoff = new Date(nowEpoch * 1e3 - 30 * 86400 * 1e3).toISOString().replace(/\.\d{3}Z$/, "Z");
  const kept = {};
  for (const [k, v] of Object.entries(s.sessions ?? {})) {
    if (k === sid || (v.last_seen ?? "") >= cutoff)
      kept[k] = v;
  }
  s.sessions = kept;
}
function tick(input) {
  const { data, now, now_epoch, session_id: sid, current_tokens, decisions } = input;
  const thresholds = data.thresholds ?? [];
  const s = clone2(input.state);
  const c = {
    s,
    data,
    now,
    nowEpoch: now_epoch,
    sid,
    currentTokens: current_tokens,
    usedPct: input.used_pct == null ? null : Number(input.used_pct),
    decisions,
    thresholds,
    maxLevel: thresholds.length - 1
  };
  migrateSchema(c);
  backfillRetroactive(c);
  assignLineage(c);
  clampLevelToXp(c);
  accumulateTokenDelta(c);
  computeMultipliers(c);
  applyRandomEvents(c);
  creditXp(c);
  resolveLevelUpAndEvolution(c);
  bumpPerTickCounters(c);
  awardBadges(c);
  pruneOldSessions(c);
  return { state: s };
}

// cli/dist/statusline.js
var RESET2 = "\x1B[0m";
var BOLD2 = "\x1B[1m";
var DIM2 = "\x1B[2m";
var WHITE = "\x1B[37m";
var CYAN = "\x1B[36m";
var YELLOW = "\x1B[33m";
var BRIGHT_RED = "\x1B[91m";
var BRIGHT_YELLOW = "\x1B[93m";
var BRIGHT_GREEN = "\x1B[92m";
var BRIGHT_MAGENTA = "\x1B[95m";
function themeAccent(theme) {
  switch (theme) {
    case "retro":
      return "\x1B[38;5;46m";
    case "dark":
      return "\x1B[38;5;51m";
    case "light":
      return "\x1B[38;5;94m";
    default:
      return "\x1B[38;5;220m";
  }
}
function ansiColor(theme, name) {
  if (theme === "retro") {
    switch (name) {
      case "dim":
        return "\x1B[38;5;22m";
      case "gold":
      case "yellow":
      case "green":
      case "cyan":
      case "white":
        return "\x1B[38;5;46m";
      case "red":
      case "magenta":
        return "\x1B[38;5;34m";
      case "blue":
        return "\x1B[38;5;28m";
      default:
        return "";
    }
  }
  switch (name) {
    case "dim":
      return "\x1B[2m";
    case "white":
      return "\x1B[37m";
    case "green":
      return "\x1B[32m";
    case "yellow":
      return "\x1B[33m";
    case "red":
      return "\x1B[31m";
    case "blue":
      return "\x1B[34m";
    case "magenta":
      return "\x1B[35m";
    case "cyan":
      return "\x1B[36m";
    case "gold":
      return themeAccent(theme);
    default:
      return "";
  }
}
function rainbowName(name) {
  const rainbows = ["\x1B[91m", "\x1B[93m", "\x1B[92m", "\x1B[96m", "\x1B[94m", "\x1B[95m"];
  let out = "";
  const chars = [...name];
  chars.forEach((ch, i) => out += rainbows[i % rainbows.length] + ch);
  return out;
}
function xpFmt(n) {
  if (n >= 1e6) {
    const v = n / 1e6;
    return v === Math.trunc(v) ? `${Math.trunc(v)}M` : `${v.toFixed(1)}M`;
  }
  if (n >= 1e3) {
    const v = n / 1e3;
    return v === Math.trunc(v) ? `${Math.trunc(v)}K` : `${v.toFixed(1)}K`;
  }
  return String(n);
}
function trimSprite(content) {
  const lines = content.split("\n");
  if (lines.length && lines[lines.length - 1] === "")
    lines.pop();
  const stripAnsi = (s) => s.replace(/\x1b\[[?0-9;]*[a-zA-Z]/g, "");
  let first = -1;
  let last = -1;
  let minLead = 0;
  let minSet = false;
  for (let i = 0; i < lines.length; i++) {
    const bare = stripAnsi(lines[i]);
    const test = bare.replace(/[ \t]+$/, "");
    if (/[^ \t]/.test(test)) {
      if (first === -1)
        first = i;
      last = i;
      const m = bare.match(/[^ \t]/);
      const lead = m ? m.index ?? 0 : 0;
      if (!minSet || lead < minLead) {
        minLead = lead;
        minSet = true;
      }
    }
  }
  if (first === -1)
    return [];
  if (!minSet)
    minLead = 0;
  const out = [];
  for (let i = first; i <= last; i++) {
    let line = lines[i].replace(/\x1b\[[?]25[lh]/g, "");
    let strip = minLead;
    while (strip > 0 && line[0] === " ") {
      line = line.slice(1);
      strip--;
    }
    out.push(line);
  }
  return out;
}
function renderInline(state, data) {
  const theme = String(data.theme ?? "default");
  const GOLD2 = themeAccent(theme);
  const lineage = state.lineage ?? "fire";
  const level = Number(state.current_level);
  const totalXp = Number(state.total_xp);
  const flash = Number(state.evolution_flash_remaining ?? 0);
  const isShiny = state.is_shiny === true;
  const thresholds = data.thresholds ?? [];
  const maxLevel = thresholds.length - 1;
  const name = evoField(data, state, lineage, level, "name");
  const emoji = evoField(data, state, lineage, level, "emoji");
  const color = evoField(data, state, lineage, level, "color");
  let shinyPrefix = "";
  let shinyColor = "";
  if (isShiny) {
    shinyPrefix = `${GOLD2}\u2605${RESET2} `;
    shinyColor = GOLD2;
  }
  if (level >= maxLevel) {
    return `${shinyPrefix}${BOLD2}${emoji} ${rainbowName(name)}${RESET2} ${BOLD2}Lv.MAX \u2726${RESET2}`;
  }
  let colorCode = color === "rainbow" ? ansiColor(theme, "gold") : ansiColor(theme, color);
  if (shinyColor)
    colorCode = shinyColor;
  let pct = progressPct(thresholds, totalXp, level);
  if (!Number.isFinite(pct))
    pct = 0;
  const currentThreshold = thresholds[level] ?? 0;
  const maxL = thresholds.length - 1;
  const nextThreshold = level >= maxL ? thresholds[maxL] : thresholds[level + 1];
  let xpInLevel = totalXp - currentThreshold;
  let nextLevelSize = nextThreshold - currentThreshold;
  if (xpInLevel < 0)
    xpInLevel = 0;
  if (nextLevelSize < 1)
    nextLevelSize = 1;
  const xpLabel = xpFmt(xpInLevel);
  const nextLabel = xpFmt(nextLevelSize);
  const pctColor = pct >= 75 ? themeAccent(theme) : "\x1B[36m";
  const gaugeWidth = 10;
  let filled = Math.trunc(pct / 10);
  if (filled > gaugeWidth)
    filled = gaugeWidth;
  if (filled < 0)
    filled = 0;
  const empty = gaugeWidth - filled;
  const gaugeFilled = "\u25B0".repeat(filled);
  const gaugeEmpty = "\u25B1".repeat(empty);
  let gaugeColor = colorCode;
  if (color === "dim" && !shinyColor)
    gaugeColor = "\x1B[96m";
  const LEVEL_COLOR = "\x1B[2m\x1B[37m";
  if (flash > 0) {
    const sparkle = "\x1B[93m\u2728\x1B[0m";
    return `${shinyPrefix}${colorCode}${BOLD2}${emoji} ${sparkle}${name}${sparkle}${RESET2} ${LEVEL_COLOR}Lv.${level}${RESET2} ${colorCode}${xpLabel}${RESET2}/${DIM2}${nextLabel}${RESET2} ${gaugeColor}${gaugeFilled}${DIM2}${gaugeEmpty}${RESET2} ${pctColor}${pct}%${RESET2}`;
  }
  return `${shinyPrefix}${colorCode}${BOLD2}${emoji} ${name}${RESET2} ${LEVEL_COLOR}Lv.${level}${RESET2} ${colorCode}${xpLabel}${RESET2}/${DIM2}${nextLabel}${RESET2} ${gaugeColor}${gaugeFilled}${DIM2}${gaugeEmpty}${RESET2} ${pctColor}${pct}%${RESET2}`;
}
function renderSpriteLines(state, data, deps) {
  const mode = String(data.display_sprite_in_statusline ?? "off");
  if (!["left", "right", "above", "true"].includes(mode))
    return [];
  const lineage = state.lineage ?? "fire";
  const level = Number(state.current_level);
  const showdownId = evoField(data, state, lineage, level, "showdown_id");
  const variant = state.is_shiny === true ? "shiny" : "normal";
  if (data.enable_animations === true) {
    const animRel = `sprites-mini-anim/${variant}/${showdownId}`;
    const nFrames = deps.animFrameCount(animRel);
    if (nFrames > 0) {
      const frameIdx = Number(state.animation_frame_index ?? 0) % nFrames;
      const frameRel = `${animRel}/frame_${String(frameIdx).padStart(2, "0")}.txt`;
      const content2 = deps.readSprite(frameRel);
      if (content2 !== null)
        return trimSprite(content2);
    }
  }
  const content = deps.readSprite(`sprites-mini/${variant}/${showdownId}.txt`);
  if (content === null)
    return [];
  return trimSprite(content);
}
function trimLastLine(line) {
  let s = line;
  let changed = true;
  while (changed) {
    changed = false;
    const t1 = s.replace(/[ \t]+$/, "");
    if (t1 !== s) {
      s = t1;
      changed = true;
    }
    const t2 = s.replace(/\x1b\[0?m$/, "");
    if (t2 !== s) {
      s = t2;
      changed = true;
    }
  }
  return s + RESET2;
}
var SPRITE_ANCHOR = "\x1B[2;30m\xB7\x1B[0m";
function renderStatusline(ctx, deps) {
  const { state, data, used, project, branch, model, effort } = ctx;
  const spriteLines = renderSpriteLines(state, data, deps);
  const n = spriteLines.length;
  let layout = String(data.display_sprite_in_statusline ?? "off");
  if (layout === "left" || layout === "right" || layout === "true")
    layout = "left";
  else if (layout === "above")
    layout = "above";
  else
    layout = "off";
  let out = "";
  if (layout === "above" && n > 0) {
    for (let i = 0; i < n; i++)
      out += `${spriteLines[i]}
`;
  }
  if (layout === "left" && n > 1) {
    for (let i = 0; i < n - 1; i++)
      out += `${SPRITE_ANCHOR}${spriteLines[i]}
`;
  }
  if (layout === "left" && n > 0) {
    out += `${SPRITE_ANCHOR}${trimLastLine(spriteLines[n - 1])}  `;
  }
  out += renderInline(state, data);
  out += `  ${DIM2}\u2502${RESET2}`;
  if (used !== "") {
    const usedInt = Math.round(Number(used));
    const gaugeTotal = 10;
    let filled = Math.trunc(usedInt * gaugeTotal / 100);
    if (filled > gaugeTotal)
      filled = gaugeTotal;
    const empty = gaugeTotal - filled;
    const gaugeColor = usedInt >= 85 ? BRIGHT_RED : usedInt >= 60 ? BRIGHT_YELLOW : BRIGHT_GREEN;
    const bar = "\u2588".repeat(filled) + "\u2591".repeat(empty);
    const mult = xpMultiplier(Number(used)).toFixed(1);
    let multColor;
    switch (mult) {
      case "2.0":
        multColor = BRIGHT_GREEN;
        break;
      case "1.5":
        multColor = "\x1B[32m";
        break;
      case "1.0":
        multColor = DIM2 + WHITE;
        break;
      case "0.5":
        multColor = BRIGHT_RED;
        break;
      default:
        multColor = WHITE;
    }
    out += `  ${gaugeColor}[${bar}]${RESET2} ${DIM2}${usedInt}%${RESET2} ${multColor}\xD7${mult}${RESET2}`;
  }
  if (project !== "")
    out += `  ${BOLD2}${CYAN}${project}${RESET2}`;
  if (branch !== "")
    out += ` ${YELLOW}${branch}${RESET2}`;
  if (model !== "")
    out += `  ${BRIGHT_MAGENTA}${model}${RESET2}`;
  if (effort !== "") {
    let label;
    let color;
    switch (effort) {
      case "low":
        label = "\u2193low";
        color = DIM2 + WHITE;
        break;
      case "medium":
        label = "\u25C7med";
        color = CYAN;
        break;
      case "high":
        label = "\u25C6high";
        color = YELLOW;
        break;
      case "xhigh":
        label = "\u25C8xhigh";
        color = BRIGHT_YELLOW;
        break;
      case "max":
        label = "\u2605max";
        color = BRIGHT_RED;
        break;
      default:
        label = effort;
        color = WHITE;
    }
    out += ` ${color}${label}${RESET2}`;
  }
  return out;
}

// cli/dist/share.js
function buildSubmitPayload(data, state, anonId, clientVer, displayName, now) {
  const share = data.stats_share ?? {};
  const ls = state.lifetime_stats ?? {};
  const orNull = (v) => v === "" ? null : v;
  return {
    anon_id: anonId,
    display_name: orNull(displayName),
    quote: orNull(share.quote ?? ""),
    bio: orNull(share.bio ?? ""),
    pinned_badges: share.pinned_badges ?? [],
    schema_version: 1,
    client_version: clientVer,
    submitted_at: now,
    stats: {
      lifetime: {
        total_tokens: ls.total_tokens ?? 0,
        total_evolutions: ls.total_evolutions ?? 0,
        total_shinies: ls.total_shinies ?? 0,
        max_level: ls.max_level ?? 0,
        total_companions: ls.total_companions ?? ls.total_compagnons ?? 0,
        lineages_completed: ls.lineages_completed ?? [],
        games_won: ls.games_won ?? 0,
        games_played: ls.games_played ?? 0
      },
      active: {
        lineage: state.lineage ?? null,
        current_level: state.current_level ?? 0,
        is_shiny: state.is_shiny ?? false
      },
      badges: (state.badges ?? []).map((b) => b.id),
      pokedex_seen_count: Object.keys(state.pokedex_wild ?? {}).length,
      pokedex_seen_ids: Object.keys(state.pokedex_wild ?? {})
    }
  };
}

// cli/dist/autosubmit.js
function planAutoSubmit(state, data, now, nowEpoch) {
  const share = data.stats_share;
  if (share?.enabled !== true)
    return null;
  const lineage = state.lineage ?? "";
  if (lineage === "" || lineage === "null")
    return null;
  const anonId = share.anon_id ?? "";
  const endpoint = share.endpoint ?? "";
  if (anonId === "" || endpoint === "")
    return null;
  const last = state.last_stats_submit_at ?? "";
  if (last !== "") {
    const lastEpoch = Math.floor(Date.parse(last) / 1e3) || 0;
    const hoursPassed = Math.floor((nowEpoch - lastEpoch) / 3600);
    if (hoursPassed < 24)
      return null;
  }
  const payload = buildSubmitPayload(data, state, anonId, String(data.version ?? "unknown"), share.display_name ?? "", now);
  return { url: `${endpoint}/v1/submit`, payload };
}

// cli/dist/entry-io.js
import { readFileSync, writeFileSync, renameSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
var POKEMON_DIR = process.env.POKEMON_DIR || join(homedir(), ".claude", "pokemon");
var DATA_PATH = join(POKEMON_DIR, "data.json");
var STATE_PATH = join(POKEMON_DIR, "state.json");
function readJsonFile(path) {
  let raw;
  try {
    raw = readFileSync(path, "utf8");
  } catch {
    return { ok: false, missing: true };
  }
  try {
    return { ok: true, value: JSON.parse(raw) };
  } catch (err) {
    return { ok: false, missing: false, error: err instanceof Error ? err.message : String(err) };
  }
}
function writeJsonAtomic(path, obj) {
  writeFileSync(path + ".tmp", JSON.stringify(obj) + "\n");
  renameSync(path + ".tmp", path);
}
function nowEpochSeconds() {
  const override = Number(process.env.POKEMON_NOW_EPOCH);
  return Number.isFinite(override) && override > 0 ? Math.floor(override) : Math.floor(Date.now() / 1e3);
}
function epochToIso(epochSeconds) {
  return new Date(epochSeconds * 1e3).toISOString().replace(/\.\d{3}Z$/, "Z");
}
var CONTENT_PATH = join(POKEMON_DIR, "content.json");
var CONFIG_PATH = join(POKEMON_DIR, "config.json");
var isObj = (v) => v !== null && typeof v === "object" && !Array.isArray(v);
function deepMerge(a, b) {
  if (!isObj(a) || !isObj(b))
    return b;
  const out = { ...a };
  for (const k of Object.keys(b))
    out[k] = k in a ? deepMerge(a[k], b[k]) : b[k];
  return out;
}
function loadData() {
  const content = readJsonFile(CONTENT_PATH);
  if (content.ok) {
    const config = readJsonFile(CONFIG_PATH);
    if (!config.ok && !config.missing)
      return { ok: false, file: "config.json", missing: false, error: config.error };
    const merged = deepMerge(content.value, config.ok ? config.value : {});
    return { ok: true, data: merged, mode: "split" };
  }
  if (!content.missing)
    return { ok: false, file: "content.json", missing: false, error: content.error };
  const legacy = readJsonFile(DATA_PATH);
  if (legacy.ok)
    return { ok: true, data: legacy.value, mode: "legacy" };
  return legacy.missing ? { ok: false, file: "data.json", missing: true } : { ok: false, file: "data.json", missing: false, error: legacy.error };
}

// cli/dist/statusline-entry.js
function lengthOf(x) {
  if (Array.isArray(x))
    return x.length;
  if (x && typeof x === "object")
    return Object.keys(x).length;
  return 0;
}
function pickStarter(data) {
  const mode = String(data.starter_pick ?? "random");
  if (mode !== "random" && data.lineages?.[mode])
    return mode;
  const keys = Object.keys(data.lineages ?? {}).sort();
  return keys[Math.floor(Math.random() * keys.length)] ?? "";
}
function rollShiny(data, state) {
  const mode = data.shiny_mode ?? "random";
  if (mode === "always")
    return true;
  if (mode === "never")
    return false;
  let chance = Number(data.shiny_chance ?? 0.01);
  if (Number(state.lifetime_stats?.total_shinies ?? 0) > 0)
    chance *= 1.25;
  if (data.shiny_hunter_mode === true)
    chance *= 5;
  return Math.random() < chance;
}
function computeDecisions(state, data) {
  const lineage = state.lineage ?? "";
  const bl = lengthOf(data.berries);
  const wl = lengthOf(data.wild_pool);
  const il = lengthOf(data.items);
  const bxmin = Number(data.battle_xp_min ?? 500);
  const bxmax = Number(data.battle_xp_max ?? 5e3);
  return {
    starter: lineage === "" ? pickStarter(data) : null,
    shiny: rollShiny(data, state),
    eevee_fallback_index: Math.floor(Math.random() * 3),
    berry: {
      fired: Math.random() < Number(data.event_chances?.berry ?? 5e-3),
      index: bl ? Math.floor(Math.random() * bl) : 0
    },
    encounter: {
      fired: Math.random() < Number(data.event_chances?.encounter ?? 1e-3),
      index: wl ? Math.floor(Math.random() * wl) : 0
    },
    battle: {
      fired: Math.random() < Number(data.battle_chance_on_encounter ?? 0.3),
      wild_level: Math.floor(Math.random() * 46) + 5,
      bonus_xp_raw: Math.floor(Math.random() * (bxmax - bxmin + 1)) + bxmin
    },
    item: {
      fired: Math.random() < Number(data.item_drop_chance_on_encounter ?? 0.3),
      index: il ? Math.floor(Math.random() * il) : 0
    }
  };
}
function gitBranch(cwd) {
  try {
    return execFileSync("git", ["-C", cwd, "symbolic-ref", "--short", "HEAD"], {
      stdio: ["ignore", "pipe", "ignore"],
      env: { ...process.env, GIT_OPTIONAL_LOCKS: "0" }
    }).toString().trim();
  } catch {
    return "";
  }
}
function basename(p) {
  const parts = p.replace(/\/+$/, "").split("/");
  return parts[parts.length - 1] || p;
}
function fireAutoSubmit(plan) {
  const code = "fetch(process.argv[1],{method:'POST',headers:{'content-type':'application/json'},body:process.argv[2],signal:AbortSignal.timeout(5000)}).catch(()=>{})";
  try {
    spawn(process.execPath, ["-e", code, plan.url, JSON.stringify(plan.payload)], {
      detached: true,
      stdio: "ignore"
    }).unref();
  } catch {
  }
}
async function readStdin() {
  const chunks = [];
  for await (const chunk of process.stdin)
    chunks.push(chunk);
  return Buffer.concat(chunks).toString("utf8");
}
function main(input) {
  const cwd = input.workspace?.current_dir ?? input.cwd ?? "";
  const model = input.model?.display_name ?? "";
  const used = input.context_window?.used_percentage;
  const usedStr = used === void 0 || used === null ? "" : String(used);
  const effort = input.effort?.level ?? "";
  const sessionId = input.session_id ?? "default";
  let contextTokens = input.context_window?.tokens ?? input.context?.tokens ?? input.context_window?.input_tokens;
  if ((contextTokens === void 0 || contextTokens === null) && usedStr !== "") {
    const defaultWindow = /1M context|\(1M\)/.test(model) ? 1e6 : 2e5;
    const windowSize = input.model?.context_window ?? input.context_window?.size ?? defaultWindow;
    contextTokens = Math.trunc(Number(used) * Number(windowSize) / 100);
  }
  contextTokens = Math.round(Number(contextTokens ?? 0)) || 0;
  const dataRead = loadData();
  if (!dataRead.ok) {
    process.stdout.write(dataRead.missing ? `\u26A0 pokemon: ${dataRead.file} absent \u2014 lance \`npx claude-pokemon install\`` : `\u26A0 pokemon: ${dataRead.file} corrompu \u2014 r\xE9pare-le ou relance \`npx claude-pokemon install\``);
    return;
  }
  const stateRead = readJsonFile(STATE_PATH);
  if (!stateRead.ok && !stateRead.missing) {
    process.stdout.write("\u26A0 pokemon: state.json corrompu \u2014 r\xE9pare-le ou restaure un backup (`npx claude-pokemon import <f>`)");
    return;
  }
  const data = dataRead.data;
  let state = stateRead.ok ? stateRead.value : {};
  const nowEpoch = nowEpochSeconds();
  const now = epochToIso(nowEpoch);
  const pct = usedStr === "" ? null : Math.round(Number(used));
  try {
    const res = tick({
      state,
      data,
      now,
      now_epoch: nowEpoch,
      session_id: sessionId,
      current_tokens: contextTokens,
      used_pct: pct,
      decisions: computeDecisions(state, data)
    });
    state = res.state;
    const plan = planAutoSubmit(state, data, now, nowEpoch);
    if (plan) {
      state.last_stats_submit_at = now;
      fireAutoSubmit(plan);
    }
    writeJsonAtomic(STATE_PATH, state);
  } catch {
  }
  const spriteDeps = {
    readSprite: (rel) => {
      try {
        return readFileSync2(join2(POKEMON_DIR, rel), "utf8");
      } catch {
        return null;
      }
    },
    animFrameCount: (rel) => {
      try {
        return readdirSync(join2(POKEMON_DIR, rel)).filter((f) => /^frame_.*\.txt$/.test(f)).length;
      } catch {
        return 0;
      }
    }
  };
  const branch = cwd ? gitBranch(cwd) : "";
  const projectDir = input.workspace?.project_dir ?? input.workspace?.current_dir ?? input.cwd ?? "";
  const project = projectDir ? basename(projectDir) : "";
  process.stdout.write(renderStatusline({ state, data, used: usedStr, project, branch, model, effort }, spriteDeps));
}
readStdin().then((raw) => {
  let input = {};
  try {
    input = JSON.parse(raw);
  } catch {
    input = {};
  }
  main(input);
});
